Repository psi4/psi4, pull requests merged in 2018-05, with the labels that each got.

#975 N-Body driver refactor (fixes #885)
  psi4/driver/driver_nbody.py
Labels: enhancement

#961 Enable faster density fitting
  psi4/driver/procrouting/proc.py
  psi4/share/psi4/plugin/dfmp2/plugin.cc.template
  psi4/src/export_fock.cc
  psi4/src/export_mints.cc
  psi4/src/psi4/dcft/dcft_compute.cc
  psi4/src/psi4/detci/ciwave.h
  psi4/src/psi4/detci/ints.cc
  psi4/src/psi4/dfep2/dfep2.cc
  psi4/src/psi4/dfep2/dfep2.h
  psi4/src/psi4/dfmp2/corr_grad.cc
  psi4/src/psi4/dfocc/df_ref.cc
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/fnocc/frozen_natural_orbitals.cc
  psi4/src/psi4/lib3index/CMakeLists.txt
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  psi4/src/psi4/libfock/CDJK.cc
  psi4/src/psi4/libfock/CMakeLists.txt
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libfock/MemDFJK.cc
  psi4/src/psi4/libfock/PKJK.cc
  psi4/src/psi4/libfock/PKmanagers.cc
  psi4/src/psi4/libfock/apps.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libfock/soscf.cc
  psi4/src/psi4/libfock/soscf.h
  psi4/src/psi4/libsapt_solver/fdds_disp.cc
  psi4/src/psi4/libsapt_solver/fdds_disp.h
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/psi4/libscf_solver/stability.cc
  psi4/src/psi4/occ/occwave.cc
  psi4/src/psi4/scfgrad/jk_grad.cc
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/read_options.cc
  tests/psi4numpy/dfmp2/input.dat
  tests/python/3-index-transforms/input.dat
  tests/python/CMakeLists.txt
  tests/python/JK_builds/CMakeLists.txt
  tests/python/JK_builds/input.dat
  tests/python/memdfjk/CMakeLists.txt
  tests/python/memdfjk/input.dat
  tests/tu1-h2o-energy/input.dat
Labels: enhancement

#978 Handle ECP's in n_frozen_core(), fixes #976
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/basisset.cc
  psi4/src/psi4/libmints/basisset.h
  tests/dfmp2-ecp/input.dat
  tests/dfmp2-ecp/output.ref
Labels: bug

#979 QC JSON Schema
  .gitignore
  .scripts/travis_print_failing.py
  doc/sphinxman/source/conf.py.in
  psi4/driver/driver.py
  psi4/driver/json_wrapper.py
  psi4/driver/molutil.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/molparse/__init__.py
  psi4/driver/qcdb/molparse/to_schema.py
  psi4/driver/qcdb/psiutil.py
  psi4/driver/qcdb/pytest/test_schema.py
  psi4/src/psi4/libmints/oeprop.cc
  tests/json/CMakeLists.txt
  tests/json/energy/CMakeLists.txt
  tests/json/energy/input.py.dat
  tests/json/gradient/CMakeLists.txt
  tests/json/schema_0_energy/CMakeLists.txt
  tests/json/schema_0_energy/input.py
  tests/json/schema_0_energy/output.json.ref
  tests/json/schema_0_gradient/CMakeLists.txt
  tests/json/schema_0_gradient/input.py
  tests/json/schema_0_gradient/output.json.ref
  tests/json/schema_0_properties/CMakeLists.txt
  tests/json/schema_0_properties/input.py
  tests/json/schema_0_properties/output.json.ref
  tests/json/v11_energy/CMakeLists.txt
  tests/json/v11_energy/input.py
  tests/json/v11_energy/output.ref
  tests/json/v11_gradient/CMakeLists.txt
  tests/json/v11_gradient/input.py
  tests/json/v11_gradient/output.ref
Labels: enhancement

#1011 QC JSON Update
  psi4/driver/json_wrapper.py
  psi4/driver/molutil.py
  psi4/driver/qcdb/molecule.py
  tests/json/CMakeLists.txt
  tests/json/schema_0_energy/CMakeLists.txt
  tests/json/schema_0_energy/input.py
  tests/json/schema_0_ghost/CMakeLists.txt
  tests/json/schema_0_ghost/input.py
  tests/json/schema_0_ghost/output.json.ref
  tests/json/schema_0_gradient/CMakeLists.txt
  tests/json/schema_0_gradient/input.py
  tests/json/schema_0_orient/CMakeLists.txt
  tests/json/schema_0_orient/input.py
  tests/json/schema_0_orient/output.json.ref
  tests/json/schema_0_properties/CMakeLists.txt
  tests/json/schema_0_properties/input.py
  tests/json/schema_0_throws/CMakeLists.txt
  tests/json/schema_0_throws/input.py
Labels: enhancement

#1015 DOC: a few more gotchas
  doc/sphinxman/source/manage_git.rst
Labels: documentation

#1012 MP2 DFJK logic fix and DFJK docs
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/proc.py
  tests/dfmp2-3/input.dat
Labels: bug, documentation

#1026 export boys localizer for plugins
  psi4/src/psi4/libmints/local.h
Labels: enhancement
