Repository psi4/psi4, pull requests merged in 2018-12, with the labels that each got.

#1398 Moves to C++14 and fixes a SAPT memory bug
  .scripts/miniconda.sh
  .travis.yml
  CMakeLists.txt
  cmake/custom_cxxstandard.cmake
  psi4/CMakeLists.txt
  psi4/psi4Config.cmake.in
  psi4/src/psi4/libsapt_solver/amplitudes.cc
  psi4/src/psi4/libsapt_solver/disp20.cc
  psi4/src/psi4/libsapt_solver/disp21.cc
  psi4/src/psi4/libsapt_solver/disp22sdq.cc
  psi4/src/psi4/libsapt_solver/disp22t.cc
  psi4/src/psi4/libsapt_solver/disp2ccd.cc
  psi4/src/psi4/libsapt_solver/disp30.cc
  psi4/src/psi4/libsapt_solver/elst10.cc
  psi4/src/psi4/libsapt_solver/elst12.cc
  psi4/src/psi4/libsapt_solver/elst13.cc
  psi4/src/psi4/libsapt_solver/exch-disp20.cc
  psi4/src/psi4/libsapt_solver/exch-disp30.cc
  psi4/src/psi4/libsapt_solver/exch-ind-disp30.cc
  psi4/src/psi4/libsapt_solver/exch-ind20.cc
  psi4/src/psi4/libsapt_solver/exch-ind30.cc
  psi4/src/psi4/libsapt_solver/exch10.cc
  psi4/src/psi4/libsapt_solver/exch11.cc
  psi4/src/psi4/libsapt_solver/exch12.cc
  psi4/src/psi4/libsapt_solver/fdds_disp.cc
  psi4/src/psi4/libsapt_solver/fdds_disp.h
  psi4/src/psi4/libsapt_solver/ind-disp30.cc
  psi4/src/psi4/libsapt_solver/ind20.cc
  psi4/src/psi4/libsapt_solver/ind22.cc
  psi4/src/psi4/libsapt_solver/ind30.cc
  psi4/src/psi4/libsapt_solver/sapt.cc
  psi4/src/psi4/libsapt_solver/sapt.h
  psi4/src/psi4/libsapt_solver/sapt0.cc
  psi4/src/psi4/libsapt_solver/sapt0.h
  psi4/src/psi4/libsapt_solver/sapt2.cc
  psi4/src/psi4/libsapt_solver/sapt2.h
  psi4/src/psi4/libsapt_solver/sapt2p.cc
  psi4/src/psi4/libsapt_solver/sapt2p.h
  psi4/src/psi4/libsapt_solver/sapt2p3.cc
  psi4/src/psi4/libsapt_solver/sapt2p3.h
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libsapt_solver/usapt0.h
  psi4/src/psi4/libsapt_solver/utils.cc
  psi4/src/psi4/sapt/wrapper.cc
Labels: Alert!, C++

#1383 Libmints Matrix: Symmetry Cleanup
  psi4/CMakeLists.txt
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/matrix.cc
  tests/pytest/test_matrix.py
Labels: C++, bug, testing

#1393 Regularize Wfn and P::e psivar access for scalars and arrays
  psi4/CMakeLists.txt
  psi4/__init__.py
  psi4/driver/driver_cbs.py
  psi4/driver/gaussian_n.py
  psi4/driver/json_wrapper.py
  psi4/driver/p4util/fcidump.py
  psi4/driver/p4util/numpy_helper.py
  psi4/driver/p4util/optproc.py
  psi4/driver/p4util/procutil.py
  psi4/driver/p4util/python_helpers.py
  psi4/driver/p4util/solvers.py
  psi4/driver/p4util/text.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/mcscf/mcscf_solver.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/sapt/sapt_mp2_terms.py
  psi4/run_psi4.py
  psi4/src/core.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/scfgrad/scf_grad.cc
  tests/dft-vv10/input.dat
  tests/pytest/test_qcvars.py
  tests/pytest/utils.py
  tests/pywrap-all/input.dat
  tests/soscf-dft/input.dat
Labels: Alert!

#1400 Expose good chunks of libmints and libciomr to plugins
  psi4/src/export_options.cc
  psi4/src/psi4/lib3index/denominator.h
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libmints/bessel.h
  psi4/src/psi4/libmints/cartesianiter.h
  psi4/src/psi4/libmints/cdsalclist.h
  psi4/src/psi4/libmints/corrtab.h
  psi4/src/psi4/libmints/deriv.cc
  psi4/src/psi4/libmints/deriv.h
  psi4/src/psi4/libmints/dipole.h
  psi4/src/psi4/libmints/ecpint.h
  psi4/src/psi4/libmints/element_to_Z.h
  psi4/src/psi4/libmints/extern.h
  psi4/src/psi4/libmints/fjt.h
  psi4/src/psi4/libmints/gaussquad.h
  psi4/src/psi4/libmints/gridblock.h
  psi4/src/psi4/libmints/gshell.h
  psi4/src/psi4/libmints/integral.h
  psi4/src/psi4/libmints/integralparameters.h
  psi4/src/psi4/libmints/local.h
  psi4/src/psi4/libmints/mintshelper.cc
  psi4/src/psi4/libmints/multipolesymmetry.h
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/oeprop.h
  psi4/src/psi4/libmints/onebody.h
  psi4/src/psi4/libmints/orbitalspace.h
  psi4/src/psi4/libmints/orthog.h
  psi4/src/psi4/libmints/osrecur.h
  psi4/src/psi4/libmints/petitelist.h
  psi4/src/psi4/libmints/pointgrp.h
  psi4/src/psi4/libmints/potentialint.h
  psi4/src/psi4/libmints/shellrotation.h
  psi4/src/psi4/libmints/sobasis.h
  psi4/src/psi4/libmints/sointegral_onebody.h
  psi4/src/psi4/libmints/sointegral_twobody.h
  psi4/src/psi4/libmints/vector.h
  psi4/src/psi4/libmints/vector3.h
  psi4/src/psi4/libmints/writer.h
  psi4/src/psi4/libmints/x2cint.h
  psi4/src/psi4/liboptions/print.cc
Labels: C++

#1415 Remove a few libmints exports
  psi4/src/psi4/libmints/ecpint.h
  psi4/src/psi4/libmints/potentialint.h
Labels: C++

#1409 Add opt-full-hess-every test only when MAX_AM_ERI is high enough
  psi4/src/psi4/libmints/integral.cc
  tests/opt-full-hess-every/CMakeLists.txt
Labels: testing

#1403 dft: "B97" conceded to Grimme
  psi4/driver/procrouting/dft/libxc_functionals.py
Labels: bug

#1416 Update pyversions in conda install docs
  doc/sphinxman/source/conda.rst
Labels: documentation

#1382 Add analytic dipole derivatives for RHF
  .travis.yml
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/qcdb/vib.py
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/dipole.cc
  psi4/src/psi4/libmints/dipole.h
  psi4/src/psi4/libmints/eribase.cc
  psi4/src/psi4/libmints/mintshelper.cc
  psi4/src/psi4/libmints/mintshelper.h
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/sieve.cc
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libmints/writer_file_prefix.h
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/psi4/scfgrad/scf_grad.h
  psi4/src/psi4/scfgrad/wrapper.cc
  tests/CMakeLists.txt
  tests/pytest/test_vibanalysis.py
  tests/scf-dipder/CMakeLists.txt
  tests/scf-dipder/input.dat
  tests/scf-dipder/output.ref
Labels: C++, enhancement

#1410 Fix path handling and psithon2 test on Windows
  psi4/driver/wrapper_database.py
  tests/psithon2/input.dat
Labels: enhancement

#1421 QCSchema update and SCF properties
  psi4/driver/driver.py
  psi4/driver/json_wrapper.py
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/read_options.cc
  tests/json/CMakeLists.txt
  tests/json/schema-1-energy/input.py
  tests/json/schema-1-properties/input.py
  tests/json/v11-energy/CMakeLists.txt
  tests/json/v11-energy/input.py
  tests/json/v11-energy/output.ref
  tests/json/v11-gradient/CMakeLists.txt
  tests/json/v11-gradient/input.py
  tests/json/v11-gradient/output.ref
  tests/pytest/test_addons.py
Labels: enhancement

#1427 Fix a memory error in psi::MOInfo::read_mo_spaces
  psi4/src/psi4/libmoinfo/moinfo.cc
Labels: bug

#1316 Molecule Provenance
  external/upstream/qcelemental/CMakeLists.txt
  psi4/driver/molutil.py
  psi4/driver/qcdb/intf_dftd3/runner.py
  psi4/driver/qcdb/libmintsmolecule.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/psiutil.py
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/molecule.h
  tests/json/schema-1-energy/input.py
  tests/pytest/test_molecule_to_string.py
Labels: schema

#1435 Fix race condition in maximum orbital gradient of parallel ODCT.
  psi4/src/psi4/dcft/dcft_oo_RHF.cc
  psi4/src/psi4/dcft/dcft_oo_UHF.cc
Labels: bug, parallelism

#1438 Fix multiple declaration of psi::cctriples::thread_data
  psi4/src/psi4/cc/cctriples/ET_RHF.cc
  psi4/src/psi4/cc/cctriples/EaT_RHF.cc
Labels: C++, bug

#1424 Symmetry-Breaking Findif, and Reference First
  psi4/driver/driver.py
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/molecule.cc
  tests/fd-freq-energy/input.dat
Labels: C++, bug

#1405 Check for explicitly defined dispersion corrections first.
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/dh_functionals.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
Labels: enhancement
