Repository psi4/psi4, pull requests merged in 2018-11, with the labels that each got.

#1326 extra findif freq file clean
  psi4/driver/driver.py
  psi4/driver/qcdb/interface_gcp.py
Labels: bug

#1314 Replace calls to deprecated LAPACK subroutines
  psi4/include/psi4/pragma.h
  psi4/src/psi4/libqt/CMakeLists.txt
  psi4/src/psi4/libqt/lapack_intfc.cc
  psi4/src/psi4/libqt/lapack_intfc_mangle.h
  psi4/src/psi4/libqt/qt.h
Labels: compatibility

#1042 nbody gradient and Hessian
  psi4/driver/driver.py
  psi4/driver/driver_nbody.py
  psi4/driver/driver_nbody_helper.py
  tests/CMakeLists.txt
  tests/nbody-convergence/CMakeLists.txt
  tests/nbody-convergence/input.dat
  tests/nbody-convergence/output.ref
  tests/nbody-cp-gradient/CMakeLists.txt
  tests/nbody-cp-gradient/input.dat
  tests/nbody-cp-gradient/output.ref
  tests/nbody-freq/CMakeLists.txt
  tests/nbody-freq/input.dat
  tests/nbody-freq/output.ref
  tests/nbody-he-cluster/input.dat
  tests/nbody-multi-level/CMakeLists.txt
  tests/nbody-multi-level/input.dat
  tests/nbody-multi-level/output.ref
  tests/nbody-nocp-gradient/CMakeLists.txt
  tests/nbody-nocp-gradient/input.dat
  tests/nbody-nocp-gradient/output.ref
  tests/nbody-vmfc-gradient/CMakeLists.txt
  tests/nbody-vmfc-gradient/input.dat
  tests/nbody-vmfc-gradient/output.ref
Labels: enhancement, python

#1330 expand pytest and qcelemental
  .travis.yml
  external/upstream/qcelemental/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/molutil.py
  psi4/driver/qcdb/cov_radii.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/parker.py
  psi4/extras.py
  psi4/run_psi4.py
  psi4/share/psi4/scripts/test_threading.py
  tests/opt-irc-3/input.dat
  tests/opt-lindep-change/input.dat
  tests/opt1/input.dat
  tests/pytest/addons.py
  tests/pytest/test_addons.py
  tests/pytest/test_molecule_to_string.py
  tests/pytest/test_psi4.py
  tests/pytest/utils.py
Labels: testing

#1336 Fix 1288: ODC Compatible with Other OO Code
  psi4/src/psi4/dcft/dcft_gradient_UHF.cc
  psi4/src/psi4/dcft/dcft_integrals_UHF.cc
  psi4/src/psi4/dcft/dcft_qc.cc
Labels: bug

#1342 Resolves configure issue in libqt wrt lapack
  psi4/src/psi4/libqt/CMakeLists.txt
Labels: build

#1276 Fix "psi4 --test" on Windows
  appveyor.yml
  tests/pytest/conftest.py
Labels: compatibility

#1352 Fix bug with setting double options to integers
  psi4/src/core.cc
Labels: bug

#1363 Make failing "psi4 --test" to return non-zero status
  psi4/run_psi4.py
Labels: compatibility

#1368 CI for Windows on Azure
  azure-pipelines.yml
Labels: build, compatibility

#1373 Adds back LAPACK target to bin/lib modules
  cmake/psi4OptionsTools.cmake
Labels: bug, build

#1377 fixes incorrect CBS delta correction for fno-ccsd
  psi4/driver/driver_cbs.py
Labels: bug

#1374 makes relativistic basis visible for SO integrals
  psi4/driver/procrouting/scf_proc/scf_iterator.py
Labels: bug

#1348 Fix OpenMP config for clang-cl on Windonws
  appveyor.yml
  external/common/lapack/FindMathOpenMP.cmake
  external/common/lapack/FindTargetOpenMP.cmake
Labels: build, compatibility

#1200 Fix OpenMP for Windows in lib3index
  psi4/src/psi4/lib3index/dfhelper.cc
Labels: C++, compatibility
