Repository psi4/psi4, pull requests merged in 2018-09, with the labels that each got.

#1199 Remove direct pthread dependency
  appveyor.yml
  psi4/CMakeLists.txt
  psi4/src/CMakeLists.txt
  psi4/src/psi4/cctriples/ET_RHF.cc
  psi4/src/psi4/cctriples/EaT_RHF.cc
  psi4/src/psi4/libdpd/cc3_sigma_RHF_ic.cc
Labels: C++, compatibility

#1130 SCF: Add SCFConvergence Error
  psi4/driver/p4util/exceptions.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  tests/scf2/input.dat
Labels: enhancement, python

#1245 CI Stability
  .travis.yml
Labels: build

#1263 Update prog_style_c.rst
  doc/sphinxman/source/prog_style_c.rst
Labels: documentation

#1237 Fix vector index error in psi::PKMgrDisk::batch_sizing
  appveyor.yml
  psi4/src/psi4/libfock/PKmanagers.cc
Labels: bug
