Repository psi4/psi4, pull requests merged in 2018-08, with the labels that each got.

#1078 Port fnocc to Windows
  psi4/include/psi4/times.h
  psi4/src/psi4/fnocc/blas.h
  psi4/src/psi4/fnocc/ccsd.cc
  psi4/src/psi4/fnocc/coupled_pair.cc
  psi4/src/psi4/fnocc/df_cc_residual.cc
  psi4/src/psi4/fnocc/df_ccsd.cc
  psi4/src/psi4/fnocc/df_scs.cc
  psi4/src/psi4/fnocc/df_t1_transformation.cc
  psi4/src/psi4/fnocc/lowmemory_triples.cc
  psi4/src/psi4/fnocc/mp2.cc
  psi4/src/psi4/fnocc/quadratic.cc
  psi4/src/psi4/fnocc/triples.cc
Labels: compatibility

#1075 Port libmints to Windows
  psi4/src/psi4/libmints/bessel.cc
  psi4/src/psi4/libmints/bessel.h
  psi4/src/psi4/libmints/chartab.cc
  psi4/src/psi4/libmints/dimension.cc
  psi4/src/psi4/libmints/dimension.h
  psi4/src/psi4/libmints/ecpint.cc
  psi4/src/psi4/libmints/get_writer_file_prefix.cc
  psi4/src/psi4/libmints/multipoles.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/writer.cc
Labels: compatibility

#1077 Port libqt to Windows
  psi4/src/psi4/libciomr/tstart.cc
  psi4/src/psi4/libqt/invert.cc
  psi4/src/psi4/libqt/mat_print.cc
  psi4/src/psi4/libqt/probabil.cc
  psi4/src/psi4/libqt/qt.h
  psi4/src/psi4/libqt/timer.cc
Labels: compatibility

#1124 Update dependencies for Windows
  external/upstream/gau2grid/CMakeLists.txt
  external/upstream/libint/CMakeLists.txt
  external/upstream/libxc/CMakeLists.txt
  psi4/CMakeLists.txt
Labels: build, compatibility

#1122 iomp5, p4c4, misc.
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CMakeLists.txt
  doc/sphinxman/source/build_faq.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/conf.py.in
  doc/sphinxman/source/external.rst
  doc/sphinxman/source/freq.rst
  doc/sphinxman/source/thermo.rst
  external/common/lapack/FindMathOpenMP.cmake
  psi4/driver/procrouting/interface_cfour.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/driver/qcdb/__init__.py
  psi4/driver/qcdb/cfour.py
  psi4/driver/qcdb/libmintsmolecule.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/options.py
  tests/cfour/psi-ghost-grad/input.dat
  tests/cfour/pywrap-cbs1/input.dat
  tests/cfour/sp-rhf-ccsd_t_-fc/input.dat
Labels: build, compatibility, documentation

#1133 Split of Prop and OEProp to allow I/O less computation of Properties without globals.
  psi4/src/export_oeprop.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/oeprop.h
Labels: C++, enhancement

#1024 FINDIF Overhaul
  doc/sphinxman/source/scf.rst
  psi4/driver/driver.py
  psi4/driver/driver_findif.py
  psi4/driver/p4util/numpy_helper.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/qcdb/__init__.py
  psi4/driver/qcdb/gradparse.py
  psi4/driver/qcdb/libmintsmolecule.py
  psi4/driver/qcdb/libmintspointgrp.py
  psi4/driver/qcdb/molecule.py
  psi4/src/CMakeLists.txt
  psi4/src/core.cc
  psi4/src/export_mints.cc
  psi4/src/psi4/CMakeLists.txt
  psi4/src/psi4/findif/CMakeLists.txt
  psi4/src/psi4/findif/fd_1_0.cc
  psi4/src/psi4/findif/fd_freq_0.cc
  psi4/src/psi4/findif/fd_freq_1.cc
  psi4/src/psi4/findif/fd_geoms_1_0.cc
  psi4/src/psi4/findif/fd_geoms_freq_0.cc
  psi4/src/psi4/findif/fd_geoms_freq_1.cc
  psi4/src/psi4/findif/fd_misc.cc
  psi4/src/psi4/findif/findif.h
  psi4/src/psi4/libmints/cdsalclist.h
  psi4/src/psi4/libmints/chartab.cc
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/molecule.h
  psi4/src/psi4/libmints/pointgrp.h
  psi4/src/psi4/libmints/vector3.h
  psi4/src/psi4/libmints/writer.cc
  psi4/src/psi4/libmints/writer.h
  psi4/src/psi4/libpsi4util/process.h
  tests/cbs-xtpl-freq/input.dat
  tests/cookbook/manual-fd-hess-energy/CMakeLists.txt
  tests/cookbook/manual-fd-hess-energy/input.dat
  tests/cookbook/manual-fd-hess-grad/CMakeLists.txt
  tests/cookbook/manual-fd-hess-grad/input.dat
  tests/cookbook/manual-sow-reap/E-input.dat
  tests/cookbook/manual-sow-reap/input.dat
  tests/cookbook/manual-sow-reap/run-psi4-disps.csh
  tests/fd-freq-energy/input.dat
  tests/fd-freq-energy/long-input.dat
  tests/fd-freq-energy/psi3-analytic.out
  tests/fd-freq-gradient/input-long.dat
  tests/fd-freq-gradient/input.dat
Labels: enhancement, python

#1115 Port build system to Windows
  .travis.yml
  CMakeLists.txt
  cmake/custom_cxxstandard.cmake
  doc/sphinxman/source/build_planning.rst
  external/common/hdf5/CMakeLists.txt
  external/common/lapack/CMakeLists.txt
  external/downstream/gpu_dfcc/CMakeLists.txt
  external/downstream/pasture/CMakeLists.txt
  external/downstream/v2rdm_casscf/CMakeLists.txt
  external/upstream/ambit/CMakeLists.txt
  external/upstream/chemps2/CMakeLists.txt
  external/upstream/dkh/CMakeLists.txt
  external/upstream/erd/CMakeLists.txt
  external/upstream/gau2grid/CMakeLists.txt
  external/upstream/gdma/CMakeLists.txt
  external/upstream/gtfock/CMakeLists.txt
  external/upstream/libefp/CMakeLists.txt
  external/upstream/libint/CMakeLists.txt
  external/upstream/libxc/CMakeLists.txt
  external/upstream/pcmsolver/CMakeLists.txt
  external/upstream/pybind11/CMakeLists.txt
  external/upstream/pylibefp/CMakeLists.txt
  external/upstream/simint/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/psi4Config.cmake.in
  psi4/run_psi4.py
  psi4/share/psi4/scripts/test_threading.py
  psi4/src/CMakeLists.txt
Labels: build, compatibility
