Repository psi4/psi4, pull requests merged in 2018-10, with the labels that each got.

#1264 Switch MSVC to LLVM compiler for Windows builds
  appveyor.yml
  psi4/src/core.cc
  psi4/src/psi4/adc/diagonalize.cc
  psi4/src/psi4/cc/ccdensity/densgrid_RHF.cc
  psi4/src/psi4/cc/ccenergy/analyze.cc
  psi4/src/psi4/cc/ccresponse/analyze.cc
  psi4/src/psi4/cc/ccresponse/scatter.cc
  psi4/src/psi4/cc/cctriples/ET_RHF.cc
  psi4/src/psi4/cc/cctriples/ET_UHF_AAA.cc
  psi4/src/psi4/cc/cctriples/ET_UHF_AAB.cc
  psi4/src/psi4/cc/cctriples/ET_UHF_ABB.cc
  psi4/src/psi4/cc/cctriples/ET_UHF_BBB.cc
  psi4/src/psi4/cc/cctriples/EaT_RHF.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libmints/benchmark.cc
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/writer.cc
  psi4/src/psi4/libqt/dx_write.cc
  psi4/src/psi4/libqt/timer.cc
  psi4/src/psi4/libtrans/fcidump_helper.cc
  psi4/src/psi4/mrcc/mrcc.cc
  psi4/src/psi4/occ/arrays.cc
  psi4/src/psi4/occ/dpd.cc
  psi4/src/psi4/optking/print.cc
  psi4/src/psi4/psimrcc/matrix.cc
Labels: build, compatibility

#1260 Dft fixes
  psi4/driver/procrouting/dft_funcs/dict_hyb_funcs.py
  psi4/driver/procrouting/dft_funcs/dict_xc_funcs.py
  psi4/src/export_functional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
Labels: bug, documentation

#1233 DFT Grid Cache and VV10 Gradients
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_functional.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/dfmp2/corr_grad.cc
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/libcubeprop/csg.cc
  psi4/src/psi4/libfock/CDJK.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libfock/DiskJK.cc
  psi4/src/psi4/libfock/MemDFJK.cc
  psi4/src/psi4/libfock/PKJK.cc
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/cubature.h
  psi4/src/psi4/libfock/dft_integrators.h
  psi4/src/psi4/libfock/gridblocker.h
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/points.cc
  psi4/src/psi4/libfock/points.h
  psi4/src/psi4/libfock/v.cc
  psi4/src/psi4/libfock/v.h
  psi4/src/psi4/libfunctional/superfunctional.cc
  psi4/src/psi4/libfunctional/superfunctional.h
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/scfgrad/jk_grad.cc
Labels: C++, enhancement, gradient

#1299 Fix #1298, full_hess_every taking hessians at the starting geometry.
  psi4/driver/driver.py
  tests/opt-full-hess-every/CMakeLists.txt
  tests/opt-full-hess-every/input.dat
Labels: bug, optking

#1300 Fix proposal for issue 1284 (SCF printing)
  psi4/src/core.cc
Labels: bug, python

#1121 shields.io update
  README.md
Labels: documentation

#1305 add coordinate data to codemeta.json to service map
  codemeta.json
Labels: documentation

#1310 Fixes #1309, clears DCT files correctly.
  psi4/src/psi4/dcft/dcft_memory.cc
Labels: C++, bug

#1151 refactor empirical dispersion
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/dft.rst
  doc/sphinxman/source/dftd3.rst
  external/upstream/pylibefp/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/molutil.py
  psi4/driver/p4util/python_helpers.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/__init__.py
  psi4/driver/procrouting/dft/__init__.py
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/dh_functionals.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/lda_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
  psi4/driver/procrouting/dft/superfunctionals.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_table.py
  psi4/driver/procrouting/proc_util.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/driver/qcdb/dashparam.py
  psi4/driver/qcdb/datastructures.py
  psi4/driver/qcdb/exceptions.py
  psi4/driver/qcdb/interface_dftd3.py
  psi4/driver/qcdb/interface_gcp.py
  psi4/driver/qcdb/intf_dftd3/__init__.py
  psi4/driver/qcdb/intf_dftd3/dashparam.py
  psi4/driver/qcdb/intf_dftd3/runner.py
  psi4/driver/qcdb/intf_dftd3/worker.py
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/psiutil.py
  psi4/driver/qcdb/pytest/test_dftd3.py
  psi4/driver/qcdb/util/__init__.py
  psi4/driver/qcdb/util/regex.py
  psi4/extras.py
  psi4/psi4Config.cmake.in
  psi4/src/export_functional.cc
  psi4/src/psi4/libdisp/dispersion.cc
  psi4/src/psi4/libdisp/dispersion.h
  psi4/src/psi4/libdisp/dispersion_defines.h
  psi4/src/psi4/libmints/molecule.h
  psi4/src/psi4/scfgrad/scf_grad.cc
  psi4/src/read_options.cc
  tests/dft-smoke/input.dat
  tests/dftd3/energy/input.dat
  tests/dftd3/grad/input.dat
  tests/dftd3/psithon2/input.dat
  tests/dftd3/version/input.dat
  tests/docs-dft/input.dat
  tests/freq-isotope2/input.dat
  tests/gcp/hf3c/input.dat
Labels: compatibility, enhancement, python

#1235 Rework of CBS to use dictionaries
  doc/sphinxman/source/cbs.rst
  psi4/driver/driver.py
  psi4/driver/driver_cbs.py
  tests/CMakeLists.txt
  tests/cbs-xtpl-dict/CMakeLists.txt
  tests/cbs-xtpl-dict/input.dat
  tests/cbs-xtpl-dict/output.ref
  tests/cbs-xtpl-freq/input.dat
  tests/cbs-xtpl-freq/output.ref
Labels: enhancement, python
