Repository psi4/psi4, pull requests merged in 2018-06, with the labels that each got.

#1035 gau2grid: ensure we get the right bf ordering
  external/upstream/gau2grid/CMakeLists.txt
  psi4/CMakeLists.txt
Labels: build

#1031 BLAS+OpenMP revamp & threading testing
  .github/CONTRIBUTING.md
  CMakeLists.txt
  README.md
  cmake/autocmake_omp.cmake
  cmake/custom_cxxstandard.cmake
  cmake/math/MathLibs.cmake
  cmake/math/MathLibsFunctions.cmake
  cmake/psi4OptionsTools.cmake
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/conf.py.in
  doc/sphinxman/source/freq.rst
  doc/sphinxman/source/introduction.rst
  external/common/lapack/CMakeLists.txt
  external/common/lapack/FindMathOpenMP.cmake
  external/common/lapack/FindTargetOpenMP.cmake
  external/common/lapack/TargetLAPACKConfig.cmake.in
  external/downstream/v2rdm_casscf/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/psi4Config.cmake.in
  psi4/share/psi4/plugin/dfmp2/plugin.cc.template
  psi4/share/psi4/scripts/test_threading.py
  psi4/src/CMakeLists.txt
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/libfunctional/CMakeLists.txt
Labels: build, documentation, enhancement

#1029 ENH: Adds timers to FISAPT
  psi4/src/psi4/fisapt/fisapt.cc
Labels: enhancement

#1030 JSON/gCP/DeepDiff v1.2 release tweaks
  psi4/driver/json_wrapper.py
  psi4/driver/molutil.py
  psi4/driver/p4util/fcidump.py
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/molparse/to_schema.py
  tests/json/CMakeLists.txt
  tests/json/schema-1-energy/CMakeLists.txt
  tests/json/schema-1-energy/input.py
  tests/json/schema-1-energy/output.json.ref
  tests/json/schema-1-ghost/CMakeLists.txt
  tests/json/schema-1-ghost/input.py
  tests/json/schema-1-ghost/output.json.ref
  tests/json/schema-1-gradient/CMakeLists.txt
  tests/json/schema-1-gradient/input.py
  tests/json/schema-1-gradient/output.json.ref
  tests/json/schema-1-orient/CMakeLists.txt
  tests/json/schema-1-orient/input.py
  tests/json/schema-1-orient/output.json.ref
  tests/json/schema-1-properties/CMakeLists.txt
  tests/json/schema-1-properties/input.py
  tests/json/schema-1-properties/output.json.ref
  tests/json/schema-1-throws/CMakeLists.txt
  tests/json/schema-1-throws/input.py
  tests/json/schema_0_energy/CMakeLists.txt
  tests/json/schema_0_ghost/CMakeLists.txt
  tests/json/schema_0_gradient/CMakeLists.txt
  tests/json/schema_0_orient/CMakeLists.txt
  tests/json/schema_0_orient/input.py
  tests/json/schema_0_properties/CMakeLists.txt
  tests/json/schema_0_throws/CMakeLists.txt
  tests/json/v11-energy/CMakeLists.txt
  tests/json/v11-energy/input.py
  tests/json/v11-energy/output.ref
  tests/json/v11-gradient/CMakeLists.txt
  tests/json/v11-gradient/input.py
  tests/json/v11-gradient/output.ref
  tests/json/v11_energy/CMakeLists.txt
  tests/json/v11_gradient/CMakeLists.txt
Labels: enhancement

#1039 misc., mostly build
  external/common/lapack/FindTargetOpenMP.cmake
  external/common/lapack/TargetLAPACKConfig.cmake.in
  psi4/CMakeLists.txt
  psi4/driver/endorsed_plugins.py
  psi4/extras.py
  psi4/psi4PluginCache.cmake.in
  psi4/run_psi4.py
  psi4/share/psi4/scripts/test_threading.py
  tests/pytest/test_addons.py
Labels: build

#1027 SF-SAPT
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/sapt.rst
  psi4/driver/procrouting/proc_table.py
  psi4/driver/procrouting/sapt/__init__.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/driver/procrouting/sapt/sapt_sf_terms.py
  psi4/src/export_fock.cc
  psi4/src/export_mints.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  tests/CMakeLists.txt
  tests/sapt-sf1/CMakeLists.txt
  tests/sapt-sf1/input.dat
  tests/sapt-sf1/output.ref
Labels: documentation, enhancement
