Repository psi4/psi4, pull requests merged in 2018-07, with the labels that each got.

#1068 Oeprop printing
  psi4/src/psi4/libmints/oeprop.cc
Labels: documentation

#1074 trivialities
  README.md
Labels: documentation

#1065 Port psimrcc to Windows
  psi4/src/psi4/psimrcc/main.cc
  psi4/src/psi4/psimrcc/mrccsd_t_compute.cc
  psi4/src/psi4/psimrcc/mrccsd_t_compute_restricted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_compute_spin_adapted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_a.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_a_restricted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_ab.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_ab_restricted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_b.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_b_restricted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_heff_restricted.cc
  psi4/src/psi4/psimrcc/mrccsd_t_setup.cc
  psi4/src/psi4/psimrcc/special_matrices.cc
  psi4/src/psi4/psimrcc/updater_mk.cc
Labels: compatibility

#1069 Port libfock to Windows
  psi4/src/psi4/libfock/apps.cc
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/hamiltonian.h
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/soscf.cc
  tests/cubeprop-esp/CMakeLists.txt
Labels: compatibility

#1072 Port lib3index to Windows
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
Labels: compatibility

#1085 Update dftd3.rst
  doc/sphinxman/source/dftd3.rst
  doc/sphinxman/source/gcp.rst
Labels: documentation

#1083 SAPT(DFT) Timers & Misc.
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/src/export_misc.cc
  psi4/src/psi4/libqt/timer.cc
Labels: enhancement

#1096 JK_Grad: Fix for disk paging after wK rewrite
  psi4/src/psi4/scfgrad/jk_grad.cc
  tests/CMakeLists.txt
  tests/dft-grad-disk/CMakeLists.txt
  tests/dft-grad-disk/input.dat
  tests/dft-grad-disk/output.ref
Labels: C++, backport, bug

#1099 CI: stop testing py27. insufficient conda pkgs to add py37
  .travis.yml
Labels: testing

#1076 Port libciomr to Windows
  psi4/src/psi4/libciomr/block_matrix.cc
  psi4/src/psi4/libciomr/init_array.cc
  psi4/src/psi4/libciomr/init_matrix.cc
  psi4/src/psi4/libciomr/int_array.cc
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libciomr/long_int_array.cc
  psi4/src/psi4/libciomr/tstart.cc
  psi4/src/psi4/libciomr/zero.cc
Labels: compatibility

#1073 Port libpsio to Windows
  psi4/src/psi4/libpsio/aio_handler.cc
  psi4/src/psi4/libpsio/close.cc
  psi4/src/psi4/libpsio/filemanager.cc
  psi4/src/psi4/libpsio/getpid.cc
  psi4/src/psi4/libpsio/init.cc
  psi4/src/psi4/libpsio/open.cc
  psi4/src/psi4/libpsio/read.cc
  psi4/src/psi4/libpsio/rename_file.cc
  psi4/src/psi4/libpsio/rw.cc
  psi4/src/psi4/libpsio/toclen.cc
  psi4/src/psi4/libpsio/tocread.cc
  psi4/src/psi4/libpsio/tocwrite.cc
  psi4/src/psi4/libpsio/volseek.cc
Labels: compatibility

#1100 dfh: fix direct_iaq memory estimate in AO_core module
  psi4/src/psi4/lib3index/dfhelper.cc
Labels: backport, bug

#1103 DFH: condense memory printing and straighten out casts
  psi4/src/psi4/lib3index/dfhelper.cc
Labels: backport

#1071 Port dcft, detci, fisapt, libdpd, libsapt_solver, libscf_solver, and mcscf to Windows
  psi4/src/psi4/dcft/dcft_tau_RHF.cc
  psi4/src/psi4/dcft/dcft_tau_UHF.cc
  psi4/src/psi4/detci/ints.cc
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/fisapt/local2.cc
  psi4/src/psi4/libdpd/T3_RHF_ic.cc
  psi4/src/psi4/libdpd/cc3_sigma_RHF_ic.cc
  psi4/src/psi4/libdpd/close.cc
  psi4/src/psi4/libdpd/split.cc
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/mom.cc
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/mcscf/scf_iterate_scf_equations.cc
Labels: compatibility

#1104 DFH: suppress DFH memory messages during SAD guess
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libscf_solver/sad.cc
Labels: backport

#1089 Add pragmas for MSVC
  psi4/include/psi4/pragma.h
Labels: C++, compatibility

#1107 Add py37 to Travis-CI
  .travis.yml
Labels: python, testing

#1105 doc: fix the img I moved in psi4media
  README.md
Labels: backport

#1090 Port core to Windows
  psi4/src/create_new_plugin.cc
Labels: C++, compatibility

#1091 Port driver to Windows
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/driver/util/tty/__init__.py
Labels: C++, compatibility
