Repository psi4/psi4, pull requests merged in 2019-01, with the labels that each got.

#1432 Fix integer overflow in psi::psi_volseek
  psi4/src/psi4/libpsio/volseek.cc
Labels: bug

#1449 remedial v2rdm
  external/common/lapack/FindTargetOpenMP.cmake
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libciomr/tstart.cc
  psi4/src/psi4/libqt/qt.h
Labels: bug, build

#1442 Fix a filesystem error in psi.driver.cbs
  psi4/driver/driver_cbs.py
Labels: bug

#1454 avoid overload_cast
  psi4/src/export_mints.cc
Labels: C++, compatibility

#1451 Fix formation of SAD fractional density matrix
  psi4/src/psi4/libscf_solver/sad.cc
Labels: bug

#1455 Deprecate c-side frequencies
  psi4/driver/driver.py
  psi4/driver/p4util/python_helpers.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/cc/ccdensity/get_moinfo.cc
  psi4/src/psi4/cc/ccenergy/get_moinfo.cc
  psi4/src/psi4/cc/cceom/get_moinfo.cc
  psi4/src/psi4/cc/cclambda/get_moinfo.cc
  psi4/src/psi4/cc/cctriples/get_moinfo.cc
  psi4/src/psi4/cctransort/cctransort.cc
  psi4/src/psi4/dcft/dcft_memory.cc
  psi4/src/psi4/detci/get_mo_info.cc
  psi4/src/psi4/dfmp2/mp2.cc
  psi4/src/psi4/dfocc/get_moinfo.cc
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/fnocc/ccsd.cc
  psi4/src/psi4/libfock/apps.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libmints/writer.cc
  psi4/src/psi4/libmoinfo/moinfo.cc
  psi4/src/psi4/libsapt_solver/sapt.cc
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libscf_solver/stability.cc
  psi4/src/psi4/mcscf/mcscf.cc
  psi4/src/psi4/occ/get_moinfo.cc
Labels: C++, compatibility

#1440 Fix memory error in psi::MultipolePropCalc::compute_mo_extents
  azure-pipelines.yml
  psi4/src/psi4/libmints/oeprop.cc
Labels: bug

#1446 JK Memory estimates and tighter bounds on DFT cache
  doc/sphinxman/source/dft.rst
  doc/sphinxman/source/dftnl.rst
  doc/sphinxman/source/scf.rst
  psi4/driver/p4util/python_helpers.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_fock.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  psi4/src/psi4/lib3index/dftensor.cc
  psi4/src/psi4/lib3index/dftensor.h
  psi4/src/psi4/lib3index/fittingmetric.cc
  psi4/src/psi4/libfock/CDJK.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libfock/DiskJK.cc
  psi4/src/psi4/libfock/GTFockJK.cc
  psi4/src/psi4/libfock/MemDFJK.cc
  psi4/src/psi4/libfock/PKJK.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libscf_solver/cuhf.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/uhf.cc
  tests/dft-custom-mgga/input.dat
  tests/opt13/input.dat
  tests/pytest/test_dfjk.py
  tests/pytest/test_jkmemory.py
  tests/python/CMakeLists.txt
  tests/python/memdfjk/CMakeLists.txt
  tests/python/memdfjk/input.py
  tests/python/memdfjk/output.ref
  tests/serial-wfn/input.dat
Labels: bug, documentation, enhancement

#1453 Fix FCIDUMP irrep ordering convention
  psi4/CMakeLists.txt
  psi4/driver/p4util/fcidump.py
  tests/fcidump/Ne.6311G.INTDUMP.ref
  tests/fcidump/Ne.C1.6311G.INTDUMP.ref
  tests/fcidump/Ne.C1.cc-pVDZ.UHF.INTDUMP.ref
  tests/fcidump/Ne.cc-pVDZ.UHF.INTDUMP.ref
  tests/pytest/conftest.py
  tests/pytest/test_fcidump_energy.py
Labels: bug

#1459 use upstream snsmp2
  external/downstream/snsmp2/CMakeLists.txt
Labels: bug, build

#1460 Implement DIIS absolute error criterion
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/psi4/libmints/matrix.h
  psi4/src/psi4/libscf_solver/cuhf.cc
  psi4/src/psi4/libscf_solver/frac.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/read_options.cc
Labels: enhancement

#1458 Finish SAD reorganization and make it the default guess
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/psi4/libscf_solver/sad.h
  psi4/src/read_options.cc
  tests/dft-grad-meta/input.dat
  tests/dft-grad-meta/output.ref
  tests/dft-grad2/input.dat
  tests/dft-grad2/output.ref
  tests/pytest/test_vibanalysis.py
  tests/scf-bs/input.dat
  tests/scf-bz2/input.dat
  tests/scf-coverage/input.dat
Labels: enhancement

#1472 Restore previous DF_FITTING_CONDITION default
  psi4/src/psi4/dfmp2/corr_grad.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/scfgrad/jk_grad.cc
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/read_options.cc
Labels: Alert!, compatibility

#1379 CoordValue/CoordEntry Cleanup and 1325 Fix
  psi4/driver/qcdb/libmintscoordentry.py
  psi4/driver/qcdb/libmintsmolecule.py
  psi4/src/psi4/libmints/coordentry.h
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/molecule.h
Labels: bug

#1350 Charge-aware frozen core
  psi4/src/psi4/libmints/basisset.cc
  psi4/src/psi4/libmints/basisset.h
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/dfmp2-ecp/output.ref
  tests/dfmp2-fc/CMakeLists.txt
  tests/dfmp2-fc/input.dat
  tests/dfmp2-fc/output.ref
  tests/sapt-ecp/CMakeLists.txt
  tests/sapt-ecp/input.dat
  tests/sapt-ecp/output.ref
Labels: bug, enhancement

#1464 big endian quadrature file
  psi4/CMakeLists.txt
  psi4/share/psi4/quadratures/1_x/R_avail.big.bin
  psi4/share/psi4/quadratures/1_x/R_avail.little.bin
  psi4/share/psi4/quadratures/1_x/error.big.bin
  psi4/share/psi4/quadratures/1_x/error.little.bin
  psi4/share/psi4/quadratures/1_x/write_binary_files.py
Labels: compatibility

#1483 Symmetrize DFMP2 gradient to largest Abelian group of the molecule
  psi4/src/psi4/dfmp2/mp2.cc
Labels: bug

#1487 DCT Gradients Compatible with ROHF Guess
  psi4/src/psi4/dcft/dcft.cc
  psi4/src/psi4/dcft/dcft_compute.cc
Labels: bug

#1481 Fix fractional SAD for minimal basis sets
  psi4/src/psi4/libscf_solver/sad.cc
  tests/sapt-ecp/input.dat
  tests/sapt-ecp/output.ref
Labels: bug

#1344 Provide Read-only access to T1/T2 python side
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/cc/CMakeLists.txt
  psi4/src/psi4/cc/amps.cc
  psi4/src/psi4/cc/ccwave.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/matrix.h
  tests/python/CMakeLists.txt
  tests/python/cc_amps/CMakeLists.txt
  tests/python/cc_amps/input.py
Labels: enhancement

#1489 Fix invalid memory access in psi::ROHF::Hx
  psi4/src/psi4/libscf_solver/rohf.cc
Labels: bug

#1493 Fix SAD guess energy printout
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/psi4/libscf_solver/cuhf.cc
  psi4/src/psi4/libscf_solver/cuhf.h
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/rhf.h
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/rohf.h
Labels: enhancement

#1349 This PR will add TDDFT and stability analysis to SCF Wavefunctions
  psi4/CMakeLists.txt
  psi4/driver/p4util/solvers.py
  psi4/driver/procrouting/response/__init__.py
  psi4/driver/procrouting/response/scf_products.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libfock/v.cc
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/uhf.cc
  tests/CMakeLists.txt
  tests/pytest/test_solvers.py
  tests/pytest/test_tdscf_excitations.py
  tests/pytest/test_tdscf_products.py
  tests/python/tddft/stab.py
Labels: compatibility, mugworthy, python

#1488 Fix memory error in psi::IntegralTransform::process_spaces
  psi4/src/psi4/libtrans/integraltransform_moinfo.cc
Labels: bug

#1495 Standardize the wfn (de)serialization path
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/proc.py
  psi4/extras.py
  tests/cookbook/rohf-orb-rot/input.dat
Labels: bug

#1494 ecp and df_fitting_condition fixes
  psi4/driver/procrouting/proc.py
  psi4/run_psi4.py
  psi4/src/export_mints.cc
  psi4/src/psi4/dfmp2/corr_grad.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/scfgrad/jk_grad.cc
  tests/CMakeLists.txt
  tests/basis-ecp/CMakeLists.txt
  tests/basis-ecp/input.dat
  tests/basis-ecp/output.ref
  tests/opt-irc-1/input.dat
  tests/sapt-ecp/input.dat
Labels: bug

#1505 mend psi4 for v2rdm
  external/downstream/v2rdm_casscf/CMakeLists.txt
  psi4/src/psi4/libmints/vector.cc
  psi4/src/psi4/libmints/vector.h
  tests/v2rdm_casscf/CMakeLists.txt
  tests/v2rdm_casscf/v2rdm7/input.dat
  tests/v2rdm_casscf/v2rdm7/output.ref
Labels: bug, build

#1502 move to upstream Libxc 4.3.0
  external/upstream/libxc/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/factory.cc
Labels: compatibility

#1470 Fix for issue #1356.
  psi4/driver/qcdb/intf_dftd3/runner.py
Labels: bug
