Repository psi4/psi4, pull requests merged in 2019-04, with the labels that each got.

#1592 missing items
  psi4/driver/qcdb/vib.py
  psi4/src/read_options.cc
Labels: backport, compatibility

#1531 Add 6-311G(2df,X) basis sets for second row atoms
  psi4/share/psi4/basis/6-311g_2df_.gbs
  psi4/share/psi4/basis/6-311g_2df_2p_.gbs
  psi4/share/psi4/basis/6-311g_2df_2pd_.gbs
  psi4/share/psi4/basis/6-311g_2df_p_.gbs
  psi4/share/psi4/basis/6-311pg_2df_.gbs
  psi4/share/psi4/basis/6-311pg_2df_2p_.gbs
  psi4/share/psi4/basis/6-311pg_2df_2pd_.gbs
  psi4/share/psi4/basis/6-311pg_2df_p_.gbs
  psi4/share/psi4/basis/6-311ppg_2df_.gbs
  psi4/share/psi4/basis/6-311ppg_2df_2p_.gbs
  psi4/share/psi4/basis/6-311ppg_2df_2pd_.gbs
  psi4/share/psi4/basis/6-311ppg_2df_p_.gbs
  psi4/share/psi4/basis/NOTES
  psi4/share/psi4/basis/primitives/polarization-6311g-_2df_.gbs
  psi4/share/psi4/basis/primitives/polarization-6311g-_2df_2p_.gbs
  psi4/share/psi4/basis/primitives/polarization-6311g-_2df_2pd_.gbs
  psi4/share/psi4/basis/primitives/polarization-6311g-_2df_p_.gbs
Labels: enhancement

#1606 Fix printout of fort.56 file for MRCC
  psi4/src/psi4/mrcc/mrcc.cc
Labels: bug, compatibility

#1550 Cleanup response code
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/psi4/scfgrad/scf_grad.cc
  psi4/src/psi4/scfgrad/scf_grad.h
  psi4/src/psi4/scfgrad/wrapper.cc
Labels: enhancement

#1605 postrelease, codereview, bots docs
  azure-pipelines.yml
  doc/sphinxman/source/manage_git.rst
  doc/sphinxman/source/manage_release.rst
  doc/sphinxman/source/prog_faq.rst
  doc/sphinxman/source/prog_style_py.rst
  external/upstream/qcengine/CMakeLists.txt
Labels: documentation

#1607 explicitly np.load(..., allow_pickle=True) since we're building objects
  psi4/driver/p4util/python_helpers.py
Labels: backport, compatibility

#1602 Fix Bugs in NBOWriter
  psi4/src/psi4/libmints/writer.cc
  tests/CMakeLists.txt
  tests/nbo/CMakeLists.txt
  tests/nbo/input.47
  tests/nbo/input.dat
  tests/nbo/output.nbo
  tests/nbo/qchem.dat
Labels: backport, bug

#1576 JSON: Moves output data to tempfile
  psi4/driver/json_wrapper.py
  tests/json/schema-1-energy/input.py
  tests/json/schema-1-energy/output.json.ref
Labels: backport

#1609 Hessian CPHF options
  psi4/src/psi4/scfgrad/response.cc
Labels: bug
