Repository psi4/psi4, pull requests merged in 2019-09, with the labels that each got.

#1401 Polarizable Embedding model
  CMakeLists.txt
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/cppe.rst
  doc/sphinxman/source/interfacing.rst
  external/upstream/CMakeLists.txt
  external/upstream/cppe/CMakeLists.txt
  external/upstream/pybind11/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/__init__.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/driver/procrouting/solvent/__init__.py
  psi4/driver/procrouting/solvent/pol_embed.py
  psi4/extras.py
  psi4/psi4Config.cmake.in
  psi4/src/core.cc
  psi4/src/psi4/cctransort/cctransort.cc
  psi4/src/psi4/libmints/electricfield.cc
  psi4/src/psi4/libmints/electricfield.h
  psi4/src/psi4/libpsipcm/psipcm.cc
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/cppe/CMakeLists.txt
  tests/cppe/pe-scf-hf/CMakeLists.txt
  tests/cppe/pe-scf-hf/input.dat
  tests/cppe/pe-scf-hf/pna_6w.pot
  tests/pytests/test_addons.py
Labels: C++, enhancement

#1718 fixing g2g ci on win
  .travis.yml
  external/upstream/gau2grid/CMakeLists.txt
  external/upstream/pybind11/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/extras.py
  psi4/share/psi4/basis/NOTES
  psi4/share/psi4/basis/cfour-qz2p.gbs
  psi4/src/psi4/libfock/points.cc
  tests/cppe/CMakeLists.txt
  tests/cppe/pe-scf-hf/CMakeLists.txt
  tests/cppe/scf-hf/CMakeLists.txt
  tests/cppe/scf-hf/input.dat
  tests/cppe/scf-hf/pna_6w.pot
  tests/json/schema-1-throws/input.py
  tests/pytests/addons.py
  tests/pytests/test_addons.py
Labels: build, compatibility, testing

#1700 Use a finalized version of the SAP potential and add relevant citations.
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/scf.rst
  psi4/src/psi4/libfock/sap.cc
Labels: enhancement

#1723 QCSchema Interace
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/driver/__init__.py
  psi4/driver/p4util/util.py
  psi4/driver/schema_wrapper.py
  psi4/extras.py
  psi4/run_psi4.py
  psi4/src/psi4/cc/ccenergy/ccenergy.cc
  psi4/src/psi4/fnocc/ccsd.cc
  psi4/src/psi4/fnocc/df_ccsd.cc
  tests/json/schema-1-energy/input.py
  tests/pytests/test_qcschema.py
  tests/pytests/utils.py
Labels: enhancement

#1714 Issue cleanup: fix various crashes.
  psi4/driver/driver_nbody.py
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/molecule.h
Labels: bug
