Repository psi4/psi4, pull requests merged in 2019-05, with the labels that each got.

#1637 Validate DOCC/SOCC; Cleanup Occupation Code in HF
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
Labels: bug

#1641 Fix documentation for writing Molden files for CI NO roots
  psi4/driver/driver.py
Labels: documentation

#1534 Fix memory leaks in the code
  psi4/src/psi4/cc/ccdensity/dump_UHF.cc
  psi4/src/psi4/cc/ccdensity/kinetic.cc
  psi4/src/psi4/cc/ccdensity/x_xi_check.cc
  psi4/src/psi4/cc/ccenergy/fock_build.cc
  psi4/src/psi4/cc/cceom/check_sum.cc
  psi4/src/psi4/cc/cclambda/check_sum.cc
  psi4/src/psi4/cc/ccresponse/ccresponse.cc
  psi4/src/psi4/cc/ccresponse/globals.h
  psi4/src/psi4/dcft/dcft_memory.cc
  psi4/src/psi4/detci/b2brepl.cc
  psi4/src/psi4/detci/odometer.cc
  psi4/src/psi4/dfocc/tensors.cc
  psi4/src/psi4/fnocc/ccsd.cc
  psi4/src/psi4/fnocc/sortintegrals.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_rd.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_rd_block.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_row_rd.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_row_wrt.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_wrt.cc
  psi4/src/psi4/libdpd/buf4_mat_irrep_wrt_block.cc
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/petitelist.cc
  psi4/src/psi4/libmints/petitelist.h
  psi4/src/psi4/libmoinfo/moinfo_base.cc
  psi4/src/psi4/libmoinfo/moinfo_base.h
  psi4/src/psi4/liboptions/print.cc
  psi4/src/psi4/libpsi4util/PsiOutStream.cc
  psi4/src/psi4/libpsi4util/exception.cc
  psi4/src/psi4/libpsi4util/exception.h
  psi4/src/psi4/mcscf/scf.cc
  psi4/src/psi4/mcscf/scf.h
  psi4/src/psi4/mrcc/mrcc.cc
  psi4/src/psi4/optking/frag_apply_frozen_constraints.cc
  psi4/src/psi4/psimrcc/psimrcc.cc
  psi4/src/psi4/psimrcc/transform.cc
  psi4/src/psi4/psimrcc/transform.h
Labels: enhancement

#1642 Fix cmake changes causing plugin link problems on Mac
  psi4/src/CMakeLists.txt
Labels: bug

#1643 Fix CBS() docs.
  psi4/driver/driver_cbs.py
Labels: documentation

#1648 Fix Windows building and packaging
  azure-pipelines.yml
  conda/win/meta.yaml
Labels: backport, build

#1499 Add CSAM screening to ERISieve
  psi4/CMakeLists.txt
  psi4/src/export_mints.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/PKmanagers.cc
  psi4/src/psi4/libfock/PKmanagers.h
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libmints/sieve.cc
  psi4/src/psi4/libmints/sieve.h
  psi4/src/read_options.cc
  tests/pytests/test_erisieve.py
Labels: C++, enhancement

#1591 DFT grid pruning
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/dft.rst
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/cubature.h
  psi4/src/psi4/libfock/v.cc
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/dft-custom-mgga/input.dat
  tests/dft-custom-mgga/output.ref
  tests/dft-grad-lr1/input.dat
  tests/dft-grad-lr1/output.ref
  tests/dft-grad-lr3/input.dat
  tests/dft-grad-lr3/output.ref
  tests/dft-grad-meta/input.dat
  tests/dft-grad-meta/output.ref
  tests/dft-grad1/input.dat
  tests/dft-grad1/output.ref
  tests/dft-grad2/input.dat
  tests/dft-grad2/output.ref
  tests/dft-omega/input.dat
  tests/dft-omega/output.ref
  tests/dft-pruning/CMakeLists.txt
  tests/dft-pruning/input.dat
  tests/dft-pruning/output.ref
  tests/dft-psivar/input.dat
  tests/dft-psivar/output.ref
  tests/dft-vv10/input.dat
  tests/dft-vv10/output.ref
  tests/dft1/input.dat
  tests/dft1/output.ref
  tests/dftd3/grad/input.dat
  tests/dftd3/grad/output.ref
  tests/dftd3/version/input.dat
  tests/dftd3/version/output.ref
  tests/frac-traverse/input.dat
  tests/frac-traverse/output.ref
  tests/opt13/input.dat
  tests/opt13/output.ref
  tests/pcmsolver/dft/input.dat
  tests/pcmsolver/dft/output.ref
  tests/pcmsolver/dipole/input.dat
  tests/pcmsolver/dipole/output.ref
Labels: enhancement
