Repository psi4/psi4, pull requests merged in 2019-02, with the labels that each got.

#1513 Update dfmp2.rst
  doc/sphinxman/source/dfmp2.rst
Labels: documentation

#1515 misc.
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/document_physconst.pl
  external/downstream/v2rdm_casscf/CMakeLists.txt
  external/upstream/chemps2/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/psifiles.py
  psi4/share/psi4/plugin/dfmp2/plugin.cc.template
  psi4/share/psi4/plugin/scf/pymodule.py.template
  psi4/share/psi4/scripts/test_threading.py
  psi4/src/read_options.cc
  tests/opt-full-hess-every/input.dat
  tests/python/cc_amps/input.py
  tests/sapt-ecp/input.dat
  tests/v2rdm_casscf/v2rdm7/CMakeLists.txt
Labels: enhancement

#1475 Fix inconsistencies in formatted checkpoint files
  psi4/driver/driver.py
  psi4/src/psi4/libmints/writer.cc
Labels: bug

#1520 openmp inheritance for plugins
  external/common/lapack/FindTargetOpenMP.cmake
  psi4/share/psi4/scripts/test_threading.py
Labels: bug

#1524 reconcile fchk and gdma fixes psi4/psi4#1523
  external/common/lapack/FindTargetOpenMP.cmake
  psi4/driver/driver.py
Labels: bug

#1525 DFT: Adds OctreeGridBlocker -> BlockOPoints pruning check.
  psi4/src/psi4/libfock/cubature.cc
Labels: bug

#1498 Implement Huckel guess
  doc/sphinxman/source/introduction.rst
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/psi4/libscf_solver/sad.h
  psi4/src/read_options.cc
  tests/opt4/psi.file11.dat
  tests/scf-guess/input.dat
  tests/scf-guess/output.ref
Labels: enhancement

#1529 Fix indexing for ghost atoms
  psi4/src/psi4/libscf_solver/sad.cc
Labels: bug

#1521 Fix a memory error in psi::MOInfo::read_mo_spaces
  psi4/src/psi4/libmoinfo/moinfo.cc
Labels: bug

#1537 release cleanup
  README.md
  doc/sphinxman/source/build_obtaining.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/conf.py.in
  psi4/driver/driver_cbs.py
  psi4/driver/p4util/python_helpers.py
  samples/scf-guess/input.dat
  samples/scf-guess/test.in
  tests/make_cmake_files.py
  tests/psitest.pl
  tests/pytest/test_dft_benchmarks.py
  tests/pywrap-db1/CMakeLists.txt
  tests/reap.py
  tests/runtest.py
  tests/tu5-sapt/CMakeLists.txt
Labels: bug

#1549 Update scf-dipder test case
  tests/scf-dipder/input.dat
Labels: testing

#1554 basis set fixes
  psi4/share/psi4/basis/def2-msvp.gbs
  psi4/share/psi4/basis/dzvp.gbs
  psi4/share/psi4/basis/primitives/diff_gbs.py
Labels: bug

#1553 json_wrapper uses qcschema_input
  doc/sphinxman/source/build_faq.rst
  doc/sphinxman/source/build_planning.rst
  psi4/driver/json_wrapper.py
  tests/json/schema-1-energy/input.py
  tests/json/schema-1-properties/input.py
Labels: schema

#1546 Still more places where DF_FITTING_CONDITION wasn't used.
  psi4/src/psi4/dfmp2/mp2.cc
  psi4/src/psi4/lib3index/dftensor.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libsapt_solver/sapt0.cc
  psi4/src/psi4/libsapt_solver/sapt2.cc
Labels: enhancement

#1556 remove unused libfock driver connections
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_table.py
  psi4/src/core.cc
  psi4/src/read_options.cc
Labels: enhancement
