Repository psi4/psi4, pull requests merged in 2019-03, with the labels that each got.

#1490 add total_disp function to fisapt.cc
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/introduction.rst
  doc/sphinxman/source/sapt.rst
  psi4/driver/procrouting/sapt/sapt_mp2_terms.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/fisapt/fisapt.h
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/sapt-exch-disp-inf/CMakeLists.txt
  tests/sapt-exch-disp-inf/input.dat
Labels: enhancement, mugworthy

#1551 dertype and gradient passing
  psi4/driver/driver.py
Labels: bug, enhancement

#1568 Makes corrections suggested by lgtm.
  psi4/driver/p4util/optproc.py
  psi4/driver/p4util/procutil.py
  psi4/driver/p4util/solvers.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/dft/superfunctionals.py
  psi4/driver/procrouting/response/scf_products.py
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/driver/qcdb/libmintsmolecule.py
Labels: compatibility

#1571 Update MKL and fix building
  azure-pipelines.yml
  conda/win/2019.1/libiomp5md.lib
  external/common/lapack/FindTargetOpenMP.cmake
Labels: backport

#1572 rejoin the rest of the world with libderiv/libderiv.h
  external/upstream/libint/CMakeLists.txt
  psi4/src/psi4/libmints/eri.h
Labels: backport, build

#1491 Adds Axilrod-Teller-Muto 3-body dispersion from DFTD3
  .travis.yml
  CMakeLists.txt
  azure-pipelines.yml
  doc/sphinxman/source/build_planning.rst
  external/upstream/CMakeLists.txt
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/driver_cbs.py
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/dh_functionals.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/intf_dftd3/__init__.py
  psi4/driver/qcdb/intf_dftd3/dashparam.py
  psi4/driver/qcdb/intf_dftd3/runner.py
  psi4/driver/qcdb/intf_dftd3/worker.py
  psi4/driver/qcdb/molecule.py
  tests/pytest/addons.py
  tests/pytest/test_dispersion.py
  tests/pytest/test_mp2d.py
  tests/pytest/test_qcng_dftd3.py
  tests/python/CMakeLists.txt
  tests/python/cc-amps/CMakeLists.txt
  tests/python/cc-amps/input.py
Labels: enhancement

#1578 update run_json and wfn qcvars
  psi4/driver/json_wrapper.py
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/cc/ccenergy/ccenergy.cc
  psi4/src/psi4/cc/cctriples/triples.cc
  psi4/src/psi4/dfmp2/mp2.cc
  psi4/src/psi4/scfgrad/wrapper.cc
  tests/json/schema-1-energy/input.py
  tests/json/schema-1-throws/input.py
  tests/scf-hess1/input.dat
Labels: schema
