Repository psi4/psi4, pull requests merged in 2019-06, with the labels that each got.

#1477 Implement SAD_SCF_TYPE = CD and PK
  psi4/src/psi4/liboptions/liboptions.cc
  psi4/src/psi4/liboptions/liboptions.h
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/sad-scf-type/CMakeLists.txt
  tests/sad-scf-type/input.dat
  tests/sad-scf-type/output.ref
Labels: enhancement

#1581 quadrature weights cutoff
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/cubature.h
  psi4/src/read_options.cc
  tests/dft-pruning/input.dat
Labels: enhancement

#1608 Fisapt extern
  psi4/driver/procrouting/proc_util.py
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  tests/CMakeLists.txt
  tests/fsapt-ext/CMakeLists.txt
  tests/fsapt-ext/README
  tests/fsapt-ext/fsapt-ref/Disp.dat
  tests/fsapt-ext/fsapt-ref/Elst.dat
  tests/fsapt-ext/fsapt-ref/Exch.dat
  tests/fsapt-ext/fsapt-ref/IndAB.dat
  tests/fsapt-ext/fsapt-ref/IndBA.dat
  tests/fsapt-ext/fsapt-ref/QA.dat
  tests/fsapt-ext/fsapt-ref/QB.dat
  tests/fsapt-ext/fsapt-ref/ZA.dat
  tests/fsapt-ext/fsapt-ref/ZB.dat
  tests/fsapt-ext/fsapt-ref/geom.xyz
  tests/fsapt-ext/input.dat
  tests/fsapt-ext/output.ref
Labels: enhancement

#1663 IRC: Displace from initial geom correctly
  psi4/src/psi4/optking/molecule_irc_step.cc
  tests/opt-irc-2/input.dat
Labels: bug, optking

#1661 mp2-d gradients
  .travis.yml
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/p4util/procutil.py
  psi4/driver/procrouting/dft/__init__.py
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/lda_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
  psi4/driver/procrouting/dft/superfunctionals.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_table.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/run_psi4.py
  tests/pytests/test_mp2d.py
  tests/pytests/test_qcel_molparse_to_string.py
  tests/pytests/test_qcng_dftd3.py
  tests/pytests/test_qcng_dftd3_mp2d.py
Labels: enhancement, gradient

#1668 relax grid point checking near machine epsilon
  tests/dft-pruning/input.dat
Labels: testing

#1594 Document code style and pre-commit hooks
  .pre-commit-config.yaml
  .travis.yml
  doc/sphinxman/source/code_style.rst
  doc/sphinxman/source/prog_faq.rst
Labels: documentation

#1542 Default cutoffs should be same
  psi4/src/psi4/scfgrad/jk_grad.cc
Labels: enhancement

#1667 Use in-core algorithm in MemDFJK
  psi4/src/psi4/lib3index/dfhelper.cc
Labels: backport, bug
