Repository psi4/psi4, pull requests merged in 2020-03, with the labels that each got.

#1823 switch out omp call
  .azure-pipelines/azure-pipelines-linux.yml
  psi4/share/psi4/basis/NOTES
  psi4/src/psi4/libfock/v.cc
  psi4/src/psi4/libsapt_solver/sapt.cc
Labels: bug

#1484 prototype basis-dependent basis guess
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/basislist.py
  psi4/driver/qcdb/basislistdunning.py
  psi4/driver/qcdb/basislistother.py
  psi4/src/read_options.cc
  tests/basis-ecp/input.dat
  tests/docs-bases/input.dat
Labels: enhancement

#1842 Update Cholesky manual references
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/scf.rst
Labels: documentation

#1829 Debug and Quarantine HF MO Hessian: OCC's Open-Heart Surgery V
  psi4/src/psi4/libdpd/contract222.cc
  psi4/src/psi4/occ/README.txt
  psi4/src/psi4/occ/kappa_orb_resp_iter.cc
  psi4/src/psi4/occ/occ_iterations.cc
  psi4/src/psi4/occ/occwave.h
  psi4/src/psi4/occ/trans_ints_rhf.cc
  psi4/src/psi4/occ/trans_ints_uhf.cc
  psi4/src/read_options.cc
Labels: bug

#1800 dipole and quadrupole arrays and units
  external/upstream/qcelemental/CMakeLists.txt
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/proc.py
  psi4/driver/schema_wrapper.py
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/detci/opdm.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/oeprop.h
  tests/cc46/input.dat
  tests/cc54/input.dat
  tests/cepa2/input.dat
  tests/cepa3/input.dat
  tests/ci-property/input.dat
  tests/cisd-h2o+-1/input.dat
  tests/fci-dipole/input.dat
  tests/fci-tdm-2/input.dat
  tests/fci-tdm/input.dat
  tests/json/schema-1-properties/input.py
  tests/mp2-property/input.dat
  tests/pcmsolver/dipole/input.dat
  tests/props2/input.dat
  tests/props3/input.dat
  tests/pytests/test_dipoles.py
  tests/pytests/test_misc.py
  tests/pytests/test_psi4.py
  tests/python/cc54/input.py
  tests/scf-property/input.dat
Labels: property, schema

#1845 vib analysis misc.
  psi4/driver/driver_findif.py
  psi4/driver/qcdb/vib.py
  tests/pytests/test_vibanalysis.py
Labels: bug

#1846 Heal Test Suite, Orbital Convergence: OCC's Open-Heart Surgery VI
  psi4/src/psi4/libdiis/diisentry.h
  psi4/src/psi4/libdiis/diismanager.cc
  psi4/src/psi4/libpsio/config.h
  psi4/src/psi4/libpsio/error.cc
  psi4/src/psi4/libpsio/read.cc
  psi4/src/psi4/occ/cepa_iterations.cc
  psi4/src/psi4/occ/iterate_t2o1_amplitudes.cc
  psi4/src/psi4/occ/manager.cc
  psi4/src/psi4/occ/occ_iterations.cc
  psi4/src/psi4/occ/occwave.cc
  psi4/src/psi4/occ/occwave.h
  psi4/src/psi4/occ/ocepa_response_pdms.cc
  psi4/src/psi4/occ/t2_2nd_general.cc
  psi4/src/psi4/occ/t2_amps.cc
  psi4/src/psi4/occ/trans_ints_rhf.cc
  psi4/src/psi4/occ/trans_ints_uhf.cc
  psi4/src/psi4/occ/update_mo.cc
  psi4/src/read_options.cc
  tests/dfmp2-4/input.dat
  tests/ocepa-freq1/input.dat
  tests/ocepa-grad1/input.dat
  tests/ocepa-grad2/input.dat
  tests/ocepa1/input.dat
  tests/ocepa2/input.dat
  tests/ocepa3/input.dat
  tests/omp2-2/input.dat
  tests/omp2-3/input.dat
  tests/omp2-grad1/input.dat
  tests/omp2-grad2/input.dat
  tests/omp2p5-1/input.dat
  tests/omp2p5-2/input.dat
  tests/omp2p5-grad1/input.dat
  tests/omp2p5-grad2/input.dat
  tests/omp3-1/input.dat
  tests/omp3-2/input.dat
  tests/omp3-3/input.dat
  tests/omp3-grad1/input.dat
  tests/omp3-grad2/input.dat
  tests/opt-irc-2/input.dat
Labels: bug

#1849 fix threading in sapt cphf
  psi4/src/psi4/libsapt_solver/sapt.cc
Labels: bug
