Repository psi4/psi4, pull requests merged in 2020-05, with the labels that each got.

#1894 Update Ca/Cb_subset docs; Add get_opdm/get_tpdm docs.
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  tests/scf-cholesky-basis/input.dat
Labels: documentation

#1900 Oeprop eval fix
  psi4/src/psi4/libmints/oeprop.cc
  tests/python/CMakeLists.txt
  tests/python/mints14/CMakeLists.txt
  tests/python/mints14/input.py
Labels: bug, parallelism

#1850 standard suite for mp2
  CMakeLists.txt
  devtools/scripts/miniconda.sh
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/p4util/exceptions.py
  psi4/driver/p4util/text.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_util.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/schema_wrapper.py
  psi4/src/psi4/cc/ccenergy/MOInfo.h
  psi4/src/psi4/cc/ccenergy/ccenergy.cc
  psi4/src/psi4/cc/ccenergy/energy.cc
  psi4/src/psi4/cc/ccenergy/mp2_energy.cc
  psi4/src/psi4/dfmp2/mp2.cc
  psi4/src/psi4/dfocc/manager.cc
  psi4/src/psi4/dfocc/manager_cd.cc
  psi4/src/psi4/dfocc/mp2_direct.cc
  psi4/src/psi4/fnocc/ccsd.cc
  psi4/src/psi4/fnocc/coupled_pair.cc
  psi4/src/psi4/fnocc/df_ccsd.cc
  psi4/src/psi4/fnocc/frozen_natural_orbitals.cc
  psi4/src/psi4/occ/cc_energy.cc
  psi4/src/psi4/occ/occwave.cc
  psi4/src/psi4/occ/postprocessing.cc
  tests/pytests/conftest.py
  tests/pytests/standard_suite_runner.py
  tests/pytests/test_mp2.py
  tests/pytests/test_standard_suite.py
  tests/pytests/utils.py
  tests/scf-cholesky-basis/input.dat
Labels: testing

#1909 Standardize CEPA/LCCD
  psi4/src/psi4/fnocc/coupled_pair.cc
  psi4/src/psi4/occ/cepa_iterations.cc
  psi4/src/psi4/occ/manager.cc
  psi4/src/psi4/occ/occ_iterations.cc
  psi4/src/psi4/occ/occwave.cc
  tests/CMakeLists.txt
  tests/cepa-module/CMakeLists.txt
  tests/cepa0-grad1/CMakeLists.txt
  tests/cepa0-grad2/CMakeLists.txt
  tests/lccd-grad1/CMakeLists.txt
  tests/lccd-grad1/input.dat
  tests/lccd-grad1/output.ref
  tests/lccd-grad2/CMakeLists.txt
  tests/lccd-grad2/input.dat
  tests/lccd-grad2/output.ref
  tests/ocepa-freq1/CMakeLists.txt
  tests/ocepa-grad1/CMakeLists.txt
  tests/ocepa-grad2/CMakeLists.txt
  tests/ocepa1/CMakeLists.txt
  tests/ocepa2/CMakeLists.txt
  tests/ocepa3/CMakeLists.txt
  tests/olccd-freq1/CMakeLists.txt
  tests/olccd-freq1/input.dat
  tests/olccd-freq1/output.ref
  tests/olccd-grad1/CMakeLists.txt
  tests/olccd-grad1/NULL
  tests/olccd-grad1/input.dat
  tests/olccd-grad1/output.ref
  tests/olccd-grad2/CMakeLists.txt
  tests/olccd-grad2/input.dat
  tests/olccd-grad2/output.ref
  tests/olccd1/CMakeLists.txt
  tests/olccd1/input.dat
  tests/olccd1/output.ref
  tests/olccd2/CMakeLists.txt
  tests/olccd2/input.dat
  tests/olccd2/output.ref
  tests/olccd3/CMakeLists.txt
  tests/olccd3/input.dat
  tests/olccd3/output.ref
Labels: compatibility
