Repository psi4/psi4, pull requests merged in 2020-07, with the labels that each got.

#1945 various fixes incl treutler gcc5
  external/downstream/cct3/CMakeLists.txt
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libmints/gshell.cc
Labels: bug

#1057 Implementation of interface to i-pi to enable molecular dynamics simulations with psi
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  psi4/driver/__init__.py
  psi4/driver/ipi_broker.py
  psi4/extras.py
  tests/pytests/test_addons.py
Labels: enhancement

#1814 TDDFT
  .pre-commit-config.yaml
  CMakeLists.txt
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/methods.rst
  doc/sphinxman/source/resources/moxy.png
  doc/sphinxman/source/tdscf.rst
  psi4/CMakeLists.txt
  psi4/driver/driver_util.py
  psi4/driver/p4util/__init__.py
  psi4/driver/p4util/exceptions.py
  psi4/driver/p4util/numpy_helper.py
  psi4/driver/p4util/solvers.py
  psi4/driver/p4util/spectrum.py
  psi4/driver/p4util/testing.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/response/scf_products.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/read_options.cc
  setup.cfg
  tests/CMakeLists.txt
  tests/pytests/tdscf_reference_data.json
  tests/pytests/test_matrix.py
  tests/pytests/test_solvers.py
  tests/pytests/test_tdscf_excitations.py
  tests/tdscf-1/CMakeLists.txt
  tests/tdscf-1/input.dat
  tests/tdscf-1/output.ref
  tests/tdscf-2/CMakeLists.txt
  tests/tdscf-2/input.dat
  tests/tdscf-2/output.ref
  tests/tdscf-3/CMakeLists.txt
  tests/tdscf-3/input.dat
  tests/tdscf-3/output.ref
  tests/tdscf-4/CMakeLists.txt
  tests/tdscf-4/input.dat
  tests/tdscf-4/output.ref
Labels: energy, enhancement, property

#1948 Usapt spin fix
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/psi4/libsapt_solver/usapt0.h
  tests/CMakeLists.txt
  tests/sapt9/CMakeLists.txt
  tests/sapt9/input.dat
  tests/sapt9/output.ref
Labels: bug

#1962 CC Density != SCF Density
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccenergy/ccenergy.cc
Labels: bug
