Repository psi4/psi4, pull requests merged in 2020-06, with the labels that each got.

#1919 CGRSolver Minor Commenting, Bug Fix
  psi4/src/psi4/libfock/solver.cc
  psi4/src/psi4/libfock/solver.h
Labels: bug

#1910 More TDMs from DETCI
  psi4/src/psi4/detci/opdm.cc
  tests/pytests/test_detci_opdm.py
Labels: property

#1926 close detci files so independent psiapi calcs possible
  psi4/driver/procrouting/proc.py
  psi4/driver/psifiles.py
  psi4/include/psi4/psifiles.h
  psi4/src/read_options.cc
  tests/pytests/standard_suite_runner.py
  tests/pytests/test_standard_suite.py
Labels: bug, testing

#1885 TDSCF psithon interface
  psi4/driver/driver.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_table.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/src/read_options.cc
  tests/tdscf-1/input.dat
  tests/tdscf-1/output.ref
  tests/tdscf-2/input.dat
  tests/tdscf-2/output.ref
  tests/tdscf-3/input.dat
  tests/tdscf-3/output.ref
  tests/tdscf-4/input.dat
  tests/tdscf-4/output.ref
Labels: energy, enhancement

#1676 Enable interoperability via The MolSSI Driver Interface
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  CMakeLists.txt
  external/upstream/CMakeLists.txt
  external/upstream/mdi/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/mdi_engine.py
  psi4/run_psi4.py
  tests/pytests/test_mdi.py
Labels: compatibility

#1928 fix UHF after RHF CCSD gradient crash
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/sortone_RHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_UHF.cc
Labels: bug

#842 UHF Hessian and gradients
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/scfgrad/jk_grad.cc
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/psi4/scfgrad/scf_grad.cc
  psi4/src/psi4/scfgrad/scf_grad.h
  psi4/src/psi4/scfgrad/wrapper.cc
  tests/CMakeLists.txt
  tests/scf-hess2/CMakeLists.txt
  tests/scf-hess2/input.dat
  tests/scf-hess2/output.ref
  tests/scf-hess3/CMakeLists.txt
  tests/scf-hess3/input.dat
  tests/scf-hess3/output.ref
  tests/scf-hess4/CMakeLists.txt
  tests/scf-hess4/input.dat
  tests/scf-hess5/CMakeLists.txt
  tests/scf-hess5/input.dat
Labels: enhancement

#1933 Keep _default_psio_manager_ alive for Process::Environment
  psi4/src/core.cc
  psi4/src/psi4/libpsi4util/process.cc
  psi4/src/psi4/libpsi4util/process.h
Labels: bug

#1938 Fix zero damping in to_print
  psi4/driver/qcdb/molecule.py
Labels: bug

#1937 stdsuite roundup for lccd
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/driver/driver_findif.py
  psi4/driver/molutil.py
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/dfocc/cc_energy.cc
  psi4/src/psi4/dfocc/dfocc.h
  psi4/src/psi4/dfocc/manager.cc
  psi4/src/psi4/dfocc/manager_cd.cc
  tests/CMakeLists.txt
  tests/freq-masses/CMakeLists.txt
  tests/freq-masses/input.dat
  tests/pytests/standard_suite_runner.py
  tests/pytests/test_qcel_molparse_to_string.py
  tests/pytests/test_standard_suite.py
Labels: testing
