Repository psi4/psi4, pull requests merged in 2020-10, with the labels that each got.

#2014 Schema: Fixes #1987
  psi4/driver/schema_wrapper.py
Labels: bug, compatibility, python

#2015 Programmer Docs
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/prog_tour.rst
  doc/sphinxman/source/prog_ways_to_add.rst
Labels: documentation

#2017 fix vv10 for clang10
  psi4/src/psi4/libfunctional/superfunctional.cc
Labels: bug

#2022 CC response vars to wfn: polar, optrot, quadrupole
  psi4/CMakeLists.txt
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/cc/ccresponse/ccresponse.cc
  psi4/src/psi4/cc/ccresponse/optrot.cc
  psi4/src/psi4/cc/ccresponse/polar.cc
  psi4/src/psi4/cc/ccresponse/roa.cc
  tests/cc46/input.dat
  tests/cc46/output.ref
  tests/pytests/test_ccresponse.py
Labels: property, schema
