Repository psi4/psi4, pull requests merged in 2020-11, with the labels that each got.

#2027 solved memory bug in libtrans when bucketSize exceeds an int
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libciomr/long_int_array.cc
  psi4/src/psi4/libtrans/integraltransform_sort_mo_tpdm.cc
Labels: bug

#2032 Add Compute Electric Field in Memory
  psi4/src/export_oeprop.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/oeprop.h
  tests/python/mints14/input.py
Labels: enhancement

#2035 Fix MBIS docs and multipole shapes
  doc/sphinxman/source/oeprop.rst
  psi4/driver/p4util/python_helpers.py
Labels: bug

#2036 add orbital occupations to qcschema wavefunction
  psi4/driver/schema_wrapper.py
  tests/pytests/test_qcschema.py
Labels: bug, schema

#1865 SAPT(DFT) dispersion hybrid xc kernel
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/sapt.rst
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/sapt/sapt_jk_terms.py
  psi4/driver/procrouting/sapt/sapt_mp2_terms.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/driver/procrouting/sapt/sapt_util.py
  psi4/src/export_functional.cc
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  psi4/src/psi4/libsapt_solver/fdds_disp.cc
  psi4/src/psi4/libsapt_solver/fdds_disp.h
  psi4/src/psi4/libsapt_solver/sapt0.cc
  psi4/src/read_options.cc
  tests/sapt-dft-api/input.dat
  tests/sapt-dft-api/output.ref
  tests/sapt-dft-lrc/input.dat
  tests/sapt-dft-lrc/output.ref
  tests/sapt-dft1/input.dat
  tests/sapt-dft1/output.ref
  tests/sapt-dft2/input.dat
  tests/sapt-dft2/output.ref
Labels: enhancement
