Repository psi4/psi4, pull requests merged in 2020-02, with the labels that each got.

#1790 NBO Fix, Py-Movement
  psi4/driver/p4util/__init__.py
  psi4/driver/p4util/writer.py
  psi4/src/psi4/libmints/writer.cc
  psi4/src/psi4/libmints/writer.h
  tests/nbo/cartesian.47
  tests/nbo/cartesian.nbo
  tests/nbo/input.dat
  tests/nbo/qchem_cartesian.dat
Labels: bug, property

#1770 Keep one-electron integrals in core (MintsHelper)
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_util.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/include/psi4/psifiles.h
  psi4/src/export_mints.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/cc/ccdensity/Gibja.cc
  psi4/src/psi4/cc/ccdensity/add_core_ROHF.cc
  psi4/src/psi4/cc/ccdensity/kinetic.cc
  psi4/src/psi4/cc/ccenergy/rotate.cc
  psi4/src/psi4/dct/dct_memory.cc
  psi4/src/psi4/dct/dct_scf_RHF.cc
  psi4/src/psi4/dct/dct_scf_UHF.cc
  psi4/src/psi4/dfocc/get_moinfo.cc
  psi4/src/psi4/dmrg/dmrgscf.cc
  psi4/src/psi4/fnocc/df_ccsd.cc
  psi4/src/psi4/libmints/mintshelper.cc
  psi4/src/psi4/libmints/mintshelper.h
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libmints/x2cint.cc
  psi4/src/psi4/libmints/x2cint.h
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libtrans/integraltransform_oei.cc
  psi4/src/psi4/libtrans/integraltransform_sort_so_tei.cc
  psi4/src/psi4/mcscf/scf_read_so_oei.cc
  psi4/src/psi4/occ/get_moinfo.cc
  psi4/src/psi4/psimrcc/main.cc
  psi4/src/psi4/psimrcc/transform.cc
  psi4/src/psi4/psimrcc/transform.h
  psi4/src/psi4/psimrcc/transform_read_so.cc
  tests/CMakeLists.txt
  tests/x2c-perturb-h/CMakeLists.txt
  tests/x2c-perturb-h/input.dat
Labels: enhancement

#1802 Fix issue with memory deallocation in the DMRG code
  psi4/src/psi4/dmrg/dmrgscf.cc
  psi4/src/psi4/libmints/mintshelper.cc
  psi4/src/psi4/libmints/mintshelper.h
Labels: bug

#1803 Fixed the error in E(30)ind (1677)
  psi4/src/psi4/libsapt_solver/amplitudes.cc
  psi4/src/psi4/libsapt_solver/ind30.cc
  psi4/src/psi4/libsapt_solver/sapt2p3.h
Labels: bug

#1809 Condense OMP, Fix Correctness Bug: OCC's Open-Heart Surgery IV
  psi4/src/psi4/occ/CMakeLists.txt
  psi4/src/psi4/occ/iterate_t2o1_amplitudes.cc
  psi4/src/psi4/occ/occ_iterations.cc
  psi4/src/psi4/occ/occwave.h
  psi4/src/psi4/occ/omp3_g_int.cc
  psi4/src/psi4/occ/omp3_t2_1st_general.cc
  psi4/src/psi4/occ/t2_2nd_general.cc
  psi4/src/psi4/occ/t2_2nd_sc.cc
  tests/omp2p5-grad2/input.dat
Labels: bug
