Repository psi4/psi4, pull requests merged in 2021-01, with the labels that each got.

#2074 fix linux azure
  .azure-pipelines/azure-pipelines-linux.yml
Labels: build

#2077 Fixing minor bug in ccresponse/roa.cc.
  psi4/src/psi4/cc/ccresponse/roa.cc
Labels: bug, property

#1946 Threaded external charge potential
  psi4/src/psi4/libmints/extern.cc
Labels: enhancement

#2082 precheck atoms for grids
  psi4/CMakeLists.txt
  psi4/src/psi4/libfock/CDJK.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libfock/DiskJK.cc
  psi4/src/psi4/libfock/GTFockJK.cc
  psi4/src/psi4/libfock/MemDFJK.cc
  psi4/src/psi4/libfock/PKJK.cc
  psi4/src/psi4/libfock/PK_workers.cc
  psi4/src/psi4/libfock/PKmanagers.cc
  psi4/src/psi4/libfock/apps.cc
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/hamiltonian.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/points.cc
  psi4/src/psi4/libfock/solver.cc
  psi4/src/psi4/libfock/soscf.cc
  psi4/src/psi4/libfock/wrapper.cc
  tests/pytests/test_raises.py
Labels: bug

#2083 cleaner print for module level errors
  psi4/run_psi4.py
Labels: bug

#2048 windows conda package through azure
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  .lgtm.yml
  CMakeLists.txt
  cmake/FindPythonLibsNew.cmake
  cmake/FindPythonModule.cmake
  cmake/TestingMacros.cmake
  conda/win/meta.yaml
  doc/sphinxman/CMakeLists.txt
  doc/sphinxman/source/build_planning.rst
  external/downstream/adcc/CMakeLists.txt
  external/downstream/psi4fockci/CMakeLists.txt
  external/downstream/snsmp2/CMakeLists.txt
  external/upstream/ambit/CMakeLists.txt
  external/upstream/gau2grid/CMakeLists.txt
  external/upstream/pcmsolver/CMakeLists.txt
  external/upstream/pylibefp/CMakeLists.txt
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/CMakeLists.txt
  psi4/driver/p4util/CMakeLists.txt
  psi4/driver/procrouting/CMakeLists.txt
  psi4/driver/procrouting/dft/CMakeLists.txt
  psi4/driver/procrouting/findif_response_utils/CMakeLists.txt
  psi4/driver/procrouting/mcscf/CMakeLists.txt
  psi4/driver/procrouting/response/CMakeLists.txt
  psi4/driver/procrouting/sapt/CMakeLists.txt
  psi4/driver/procrouting/scf_proc/CMakeLists.txt
  psi4/driver/procrouting/solvent/CMakeLists.txt
  psi4/psi4.bat
  psi4/psi4Config.cmake.in
  psi4/psi4PluginCache.cmake.in
  psi4/run_psi4.py
  psi4/src/CMakeLists.txt
  psi4/src/psi4/libpsio/read.cc
  tests/CMakeLists.txt
  tests/pytests/CMakeLists.txt
Labels: build

#1101 move to gitlab Libxc5
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  CMakeLists.txt
  conda/win/meta.yaml
  external/upstream/libint2/CMakeLists.txt
  external/upstream/libxc/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/dh_functionals.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
  psi4/driver/procrouting/dft/superfunctionals.py
  psi4/src/export_functional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.h
  tests/dft-grad-lr2/input.dat
  tests/pytests/test_dft_benchmarks.py
Labels: C++, compatibility

#2091 tighten fchk runtime criteria and regenerate refs
  .azure-pipelines/azure-pipelines-windows.yml
  tests/pytests/test_fchk_writer.py
  tests/pytests/test_fchk_writer/rhf-cc2.ref
  tests/pytests/test_fchk_writer/rhf-ccsd.ref
  tests/pytests/test_fchk_writer/rhf-dct.ref
  tests/pytests/test_fchk_writer/rhf-hf.ref
  tests/pytests/test_fchk_writer/rhf-mp2.ref
  tests/pytests/test_fchk_writer/rhf-omp2.ref
  tests/pytests/test_fchk_writer/rhf-pbe.ref
  tests/pytests/test_fchk_writer/uhf-ccsd.ref
  tests/pytests/test_fchk_writer/uhf-hf.ref
  tests/pytests/test_fchk_writer/uhf-mp2.ref
  tests/pytests/test_fchk_writer/uhf-pbe.ref
Labels: testing

#2094 remove time test for multithread
  tests/pytests/conftest.py
  tests/pytests/test_triplet.py
Labels: testing

#2072 OCC Densities to Wavefunction
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/occ/coord_grad.cc
Labels: property

#2092 Deprecate `Matrix::SaveType::Full`
  psi4/src/psi4/dfmp2/mp2.cc
  psi4/src/psi4/libmints/eri.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/matrix.h
  psi4/src/psi4/libmints/siminteri.h
Labels: bug
