Repository psi4/psi4, pull requests merged in 2021-06, with the labels that each got.

#2188 keep_intcos works for successful optimization
  psi4/src/psi4/optking/optking.cc
Labels: bug, optking

#2193 Major bugfix! Parallelization error in DF gradients
  psi4/src/psi4/libmints/mintshelper.cc
Labels: bug, gradient, parallelism

#2156 Print extra output from TDSCF / TDDFT calculations
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/src/read_options.cc
Labels: enhancement

#2207 Fix wB97X-D3 and add KMLYP
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  tests/pytests/data_dft-bench/erkale_cation_data.tar
  tests/pytests/data_dft-bench/erkale_water_data.tar
  tests/pytests/data_dft-bench/erkale_water_dimer_data.tar
  tests/pytests/test_dft_benchmarks.py
Labels: bug
