Repository psi4/psi4, pull requests merged in 2021-11, with the labels that each got.

#2345 Less `cubeprop` manual memory management
  psi4/src/psi4/libcubeprop/csg.cc
  psi4/src/psi4/libcubeprop/csg.h
Labels: cleanup, cubeprop

#2325 Modernize `libdiis` Pointers
  psi4/src/psi4/libdiis/diisentry.cc
  psi4/src/psi4/libdiis/diisentry.h
  psi4/src/psi4/libdiis/diismanager.cc
  psi4/src/psi4/libdiis/diismanager.h
Labels: cleanup

#2346 Clean libmints `new`/`delete`
  psi4/src/psi4/libmints/basisset.cc
  psi4/src/psi4/libmints/basisset.h
  psi4/src/psi4/libmints/cartesianiter.cc
  psi4/src/psi4/libmints/cartesianiter.h
  psi4/src/psi4/libmints/cdsalclist.cc
  psi4/src/psi4/libmints/factory.cc
  psi4/src/psi4/libmints/factory.h
  psi4/src/psi4/libmints/irrep.cc
  psi4/src/psi4/libmints/local.cc
  psi4/src/psi4/libmints/molecule.cc
  psi4/src/psi4/libmints/molecule.h
  psi4/src/psi4/libmints/multipolesymmetry.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/osrecur.cc
  psi4/src/psi4/libmints/pointgrp.h
  psi4/src/psi4/libmints/vector.cc
  psi4/src/psi4/libmints/vector.h
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libscf_solver/hf.cc
Labels: libmints, cleanup, efficiency

#2349 Fix `qcdb` memory leak
  psi4/driver/qcdb/libmintsbasisset.py
Labels: efficiency

#2352 Fix memory leak of all DFT integration coordinates
  psi4/src/psi4/libfock/points.cc
Labels: dft, efficiency

#2350 Fix DIIS memory leak
  psi4/src/psi4/dlpno/mp2.cc
  psi4/src/psi4/libdiis/diisentry.cc
  psi4/src/psi4/libdiis/diisentry.h
  psi4/src/psi4/libdiis/diismanager.cc
Labels: efficiency

#2347 Fix SCF memory leak and `Vector::gemv`
  psi4/src/psi4/libmints/vector.cc
  psi4/src/psi4/libscf_solver/hf.cc
Labels: bug, scf, libmints, cleanup, efficiency

#2348 Remove unused solvers
  psi4/src/psi4/libfock/apps.cc
  psi4/src/psi4/libfock/apps.h
  psi4/src/psi4/libfock/hamiltonian.cc
  psi4/src/psi4/libfock/hamiltonian.h
  psi4/src/psi4/libfock/solver.cc
  psi4/src/psi4/libfock/solver.h
  psi4/src/psi4/libfock/wrapper.cc
  psi4/src/psi4/scfgrad/response.cc
  psi4/src/read_options.cc
Labels: cleanup

#2355 Vectorize libdiis
  .azure-pipelines/azure-pipelines-windows.yml
  psi4/src/psi4/libdiis/diismanager.cc
  psi4/src/psi4/libqt/blas_intfc.cc
  psi4/src/psi4/libqt/qt.h
Labels: efficiency

#2155 Density-based Integral Screening and Incremental Fock Build
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_fock.cc
  psi4/src/export_mints.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/psi4/libmints/twobody.cc
  psi4/src/psi4/libmints/twobody.h
  psi4/src/psi4/libscf_solver/sad.cc
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/density-screen-1/CMakeLists.txt
  tests/density-screen-1/input.dat
  tests/density-screen-1/output.ref
  tests/density-screen-2/CMakeLists.txt
  tests/density-screen-2/input.dat
  tests/density-screen-2/output.ref
  tests/pytests/test_erisieve.py
Labels: scf, feature

#2361 native_files field for qcschema
  external/upstream/qcelemental/CMakeLists.txt
  psi4/driver/schema_wrapper.py
Labels: schema
