Repository psi4/psi4, pull requests merged in 2021-09, with the labels that each got.

#2285 Cleanup `form_FDSmSDF`
  psi4/src/psi4/libscf_solver/hf.cc
Labels: scf, cleanup

#2142 empirical disp updates
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/dftd3.rst
  psi4/driver/molutil.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc.py
  psi4/driver/qcdb/molecule.py
  psi4/extras.py
  tests/CMakeLists.txt
  tests/dftd4/CMakeLists.txt
  tests/dftd4/energy/CMakeLists.txt
  tests/dftd4/energy/input.dat
  tests/dftd4/energy/output.ref
  tests/pytests/test_addons.py
Labels: feature, external-interface

#2283 Make combined omega DF algorithm consistent with uncombined version.
  psi4/src/psi4/lib3index/dfhelper.cc
Labels: backport, correctness-error
