Repository psi4/psi4, pull requests merged in 2021-12, with the labels that each got.

#2367 Pull in extra TDSCF documentation
  doc/sphinxman/source/tdscf.rst
Labels: documentation

#2368 add optional ecpint to buildsys
  CMakeLists.txt
  external/upstream/CMakeLists.txt
  external/upstream/ecpint/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/extras.py
  psi4/psi4Config.cmake.in
  psi4/src/psi4/libmints/CMakeLists.txt
  psi4/src/psi4/scfgrad/CMakeLists.txt
Labels: build, external-interface, ecpint-needed

#2370 Fixes to MBIS volume ratios
  psi4/driver/p4util/prop_util.py
  psi4/driver/p4util/python_helpers.py
  psi4/driver/p4util/util.py
  psi4/driver/procrouting/proc.py
  tests/mbis-6/input.dat
  tests/mbis-6/output.ref
Labels: property

#2378 DLPNO-MP2 Performance Improvement
  .azure-pipelines/azure-pipelines-windows.yml
  psi4/src/psi4/dlpno/mp2.cc
  psi4/src/psi4/dlpno/mp2.h
Labels: efficiency

#2377 Make ENABLE_XHOST flag checks dependent on compiler brand.
  CMakeLists.txt
Labels: build

#2381 Remove Unnecessary, Buggy `dct` Convergence Metric
  psi4/src/psi4/dct/dct.h
  psi4/src/psi4/dct/dct_compute_RHF.cc
  psi4/src/psi4/dct/dct_compute_UHF.cc
  psi4/src/psi4/dct/dct_oo_RHF.cc
  psi4/src/psi4/dct/dct_oo_UHF.cc
  psi4/src/psi4/dct/dct_qc.cc
Labels: bug, dct

#2383 DMRG Memory/`const` Cleanup
  psi4/src/psi4/dmrg/dmrgscf.cc
Labels: cleanup
