Repository psi4/psi4, pull requests merged in 2022-11, with the labels that each got.

#2759 Fix crash on CBS finite-difference with zero dipole moment
  psi4/driver/driver_cbs.py
  psi4/driver/driver_findif.py
Labels: bug, driver

#2764 misc updates, incl. py311
  .azure-pipelines/azure-pipelines-windows.yml
  CMakeLists.txt
  external/upstream/qcelemental/CMakeLists.txt
  psi4/driver/driver_nbody.py
  psi4/driver/inputparser.py
  psi4/src/psi4/libfock/cubature.cc
Labels: build

#2758 Modify Instability Following Step
  psi4/src/psi4/libscf_solver/stability.cc
  psi4/src/psi4/libscf_solver/stability.h
Labels: scf

#2762 CompositeJK Part 1: DFJLinK
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_fock.cc
  psi4/src/psi4/libfock/CMakeLists.txt
  psi4/src/psi4/libfock/DFJLinK.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/read_options.cc
  samples/linK-1/input.dat
  samples/linK-1/test.in
  samples/linK-2/input.dat
  samples/linK-2/test.in
  samples/linK-3/input.dat
  samples/linK-3/test.in
  tests/linK-1/input.dat
  tests/linK-1/output.ref
  tests/linK-2/input.dat
  tests/linK-2/output.ref
  tests/linK-3/input.dat
  tests/linK-3/output.ref
Labels: scf

#2763 PK Bugfix
  conda/win/meta.yaml
  psi4/src/psi4/libfock/PKmanagers.cc
Labels: bug, scf

#2756 Improve PSIO error messages for READ, WRITE and LSEEK
  psi4/src/psi4/libpsio/CMakeLists.txt
  psi4/src/psi4/libpsio/compose_err_msg.cc
  psi4/src/psi4/libpsio/psio.h
  psi4/src/psi4/libpsio/rw.cc
  psi4/src/psi4/libpsio/toclen.cc
  psi4/src/psi4/libpsio/volseek.cc
Labels: cleanup

#2768 Expand Testing of COSX and LINK SCF Types
  samples/scf5/input.dat
  samples/scf5/test.in
  tests/scf5/input.dat
  tests/scf5/output.ref
Labels: testing, scf

#2772 Remove new from v.cc
  psi4/src/psi4/libfock/v.cc
Labels: cleanup, dft

#2773 Fix possible infinite recursion in psio_error when the scratch disk is completely full
  psi4/src/psi4/libpsio/error.cc
Labels: libpsio

#2771 Fix some incorrect printf format specifiers
  psi4/src/psi4/cctransort/cctransort.cc
  psi4/src/psi4/cctransort/memcheck.cc
  psi4/src/psi4/detci/olsengraph.cc
  psi4/src/psi4/dlpno/mp2.cc
  psi4/src/psi4/fnocc/lowmemory_triples.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/solver.cc
  psi4/src/psi4/libmints/cdsalclist.cc
  psi4/src/psi4/libmints/extern.cc
  psi4/src/psi4/libmints/extern.h
Labels: cleanup

#2766 Modernize UHF Instability Following
  doc/sphinxman/source/scf.rst
  psi4/driver/p4util/solvers.py
  psi4/driver/procrouting/response/scf_products.py
  psi4/driver/procrouting/response/scf_response.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/driver/procrouting/scf_proc/subclass_methods.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libfock/hamiltonian.cc
  psi4/src/psi4/libfock/hamiltonian.h
  psi4/src/psi4/libfock/solver.cc
  psi4/src/psi4/libfock/solver.h
  psi4/src/psi4/libscf_solver/CMakeLists.txt
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/stability.cc
  psi4/src/psi4/libscf_solver/stability.h
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/libscf_solver/uhf.h
  psi4/src/read_options.cc
  samples/stability3/input.dat
  samples/stability3/test.in
  tests/CMakeLists.txt
  tests/sapt7/output.ref
  tests/scf-coverage/output.ref
  tests/stability1/output.ref
  tests/stability2/output.ref
  tests/stability3/CMakeLists.txt
  tests/stability3/input.dat
  tests/stability3/output.ref
  tests/stability3/test_input.py
Labels: scf, feature, cleanup

#2778 Use LAPACK for Linear Algebra in `occ`
  doc/sphinxman/source/occ.rst
  psi4/src/psi4/occ/arrays.cc
  psi4/src/psi4/occ/arrays.h
  psi4/src/psi4/occ/kappa_orb_resp.cc
  psi4/src/psi4/occ/occwave.cc
  psi4/src/psi4/occ/occwave.h
  psi4/src/psi4/occ/z_vector.cc
  psi4/src/read_options.cc
Labels: cleanup, occ

#2782 Modernize `cc` Virial Theorem
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/psi4/cc/ccdensity/kinetic.cc
  tests/cc1/input.dat
Labels: cc, cleanup

#2786 Remove CC density writing
  psi4/src/psi4/cc/ccdensity/CMakeLists.txt
  psi4/src/psi4/cc/ccdensity/Params.h
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/densgrid_RHF.cc
  psi4/src/psi4/cc/ccdensity/get_params.cc
  psi4/src/read_options.cc
Labels: cc, cleanup

#2787 Remove deprecated scf gradient tech
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/deriv.cc
  psi4/src/psi4/libmints/deriv.h
Labels: libmints, cleanup

#2481 SAPT(DFT) MO disk I/O optimization & Exchange-Dispersion scaling scheme update
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/sapt.rst
  psi4/driver/procrouting/proc_util.py
  psi4/driver/procrouting/sapt/sapt_mp2_terms.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/driver/procrouting/sapt/sapt_util.py
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libsapt_solver/fdds_disp.cc
  psi4/src/read_options.cc
  tests/sapt-compare/CMakeLists.txt
  tests/sapt-compare/test_input.py
  tests/sapt-dft-api/input.dat
  tests/sapt-dft-api/output.ref
  tests/sapt-dft1/input.dat
  tests/sapt-dft1/output.ref
  tests/sapt-dft2/input.dat
  tests/sapt-dft2/output.ref
Labels: dft, efficiency, sapt

#2784 Add shorthand for SPW92 functional
  psi4/driver/procrouting/dft/lda_functionals.py
  tests/dft1/input.dat
Labels: dft

#2686 Replace sq_rsp(...) with a new DSYEV wrapper, part 1
  psi4/src/psi4/cc/ccenergy/d1diag.cc
  psi4/src/psi4/cc/ccenergy/d2diag.cc
  psi4/src/psi4/cc/ccenergy/new_d1diag.cc
  psi4/src/psi4/detci/h0block.cc
  psi4/src/psi4/detci/sem.cc
  psi4/src/psi4/libciomr/CMakeLists.txt
  psi4/src/psi4/libciomr/dsyev_ascending.cc
  psi4/src/psi4/libciomr/dsyev_descending.cc
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libqt/david.cc
  psi4/src/psi4/libsapt_solver/sapt2.cc
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/mcscf/matrix_base.cc
  psi4/src/psi4/mcscf/scf_energy.cc
Labels: cleanup

#2790 qcng deps in docs
  CMakeLists.txt
  doc/sphinxman/source/build_planning.rst
Labels: documentation

#2807 fix docs build on master
  .github/workflows/docs-pr.yml
  .github/workflows/docs.yml
  devtools/conda-envs/docs-cf.yaml
Labels: build

#2798 Deprecate PSI_API diagonalizers rsp(...) and sq_rsp(...)
  psi4/src/psi4/libciomr/libciomr.h
Labels: cleanup

#2809 Remove deprecated
  psi4/driver/frac.py
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/proc.py
  psi4/src/core.cc
  psi4/src/export_plugins.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libmints/deriv.cc
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libpsi4util/process.cc
  psi4/src/psi4/libpsi4util/process.h
  psi4/src/psi4/libscf_solver/hf.cc
Labels: cleanup

#2792 CompositeJK Part 1.5: DFJLinK/DFJCOSK IncFock Standardization
  psi4/src/psi4/libfock/DFJLinK.cc
  psi4/src/psi4/libfock/jk.h
  tests/linK-1/input.dat
  tests/linK-2/input.dat
  tests/linK-3/input.dat
Labels: scf

#2815 bump libxc and revert qcng
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/ecosystem.yml
  conda/win/meta.yaml
  external/upstream/libxc/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
Labels: build
