Repository psi4/psi4, pull requests merged in 2022-07, with the labels that each got.

#2624 Fix Numpy Python detection in Windows for new NumPy
  .azure-pipelines/azure-pipelines-windows.yml
  CMakeLists.txt
  conda/win/meta.yaml
Labels: build, backport

#2626 Replace `get_int_array` with `get_int_vector`
  psi4/src/psi4/adc/adc.cc
  psi4/src/psi4/adc/adc.h
  psi4/src/psi4/adc/compute_energy.cc
  psi4/src/psi4/cc/ccdensity/get_rho_params.cc
  psi4/src/psi4/cc/cclambda/get_params.cc
  psi4/src/psi4/dmrg/dmrgscf.cc
  psi4/src/psi4/liboptions/liboptions.cc
  psi4/src/psi4/liboptions/liboptions.h
Labels: cleanup, efficiency

#2625 Intel compiler vs DirectJK
  psi4/src/psi4/libfock/DirectJK.cc
Labels: bug, build

#2632 testing dedup, stdsuite upgrades
  .azure-pipelines/azure-pipelines-windows.yml
  devtools/scripts/ci_run_test.py
  psi4/CMakeLists.txt
  tests/pytests/standard_suite_ref_local.py
  tests/pytests/standard_suite_runner.py
  tests/pytests/test_standard_suite.py
Labels: testing

#2643 Use Libxc setters for omega
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.h
  psi4/src/psi4/libfunctional/factory.cc
  psi4/src/psi4/libfunctional/functional.cc
  psi4/src/psi4/libfunctional/functional.h
  psi4/src/psi4/libfunctional/superfunctional.cc
  psi4/src/psi4/libfunctional/superfunctional.h
Labels: external-interface, dft
