Repository psi4/psi4, pull requests merged in 2022-09, with the labels that each got.

#2704 Chip away at MOInfo (2/???)
  psi4/src/psi4/cc/ccenergy/get_moinfo.cc
  psi4/src/psi4/cc/ccenergy/t1.cc
  psi4/src/psi4/cc/ccwave.h
Labels: cc, cleanup

#2715 Chip away at MOInfo (3/???)
  psi4/src/psi4/cc/ccenergy/Wmbej.cc
  psi4/src/psi4/cc/ccenergy/t1_ijab.cc
  psi4/src/psi4/cc/ccenergy/t2.cc
  psi4/src/psi4/cc/ccenergy/taut.cc
Labels: cc, cleanup

#2719 Clean `ccenergy/rotate` (1/2)
  psi4/src/psi4/cc/ccenergy/rotate.cc
  psi4/src/psi4/cc/ccwave.h
  tests/cc15/output.ref
  tests/cc16/output.ref
Labels: cc, cleanup

#2714 Close #2712
  psi4/src/core.cc
  psi4/src/psi4/scfgrad/scf_grad.cc
  psi4/src/psi4/scfgrad/scf_grad.h
  psi4/src/psi4/scfgrad/wrapper.cc
  tests/pytests/test_gradients.py
Labels: scf, crash

#2711 Renovate the psio_error(...) function
  psi4/src/psi4/libpsio/error.cc
  psi4/src/psi4/libpsio/psio.h
Labels: cleanup

#2720 Remove QT ordering from ccenergy
  psi4/src/psi4/cc/ccenergy/MOInfo.h
  psi4/src/psi4/cc/ccenergy/get_moinfo.cc
Labels: cc, cleanup

#2721 Mark `Matrix::get_block` const
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/matrix.h
Labels: libmints
