Repository psi4/psi4, pull requests merged in 2022-12, with the labels that each got.

#2812 Remove add_ref.cc
  psi4/src/psi4/cc/ccdensity/CMakeLists.txt
  psi4/src/psi4/cc/ccdensity/add_ref.cc
Labels: cc, cleanup

#2808 IncFock Standardization Part 2: DirectJK
  .azure-pipelines/azure-pipelines-windows.yml
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/jk.h
Labels: scf

#2813 Remove superfluous PsiOutStream includes
  psi4/src/psi4/cc/ccenergy/d1diag.cc
  psi4/src/psi4/cc/ccenergy/d2diag.cc
  psi4/src/psi4/cc/ccenergy/new_d1diag.cc
  psi4/src/psi4/libqt/david.cc
  psi4/src/psi4/mcscf/matrix_base.cc
Labels: cleanup

#2819 fix cookbooks after set_frequencies removed
  codemeta.json
  psi4/header.py
  tests/cookbook/manual-fd-hess-energy/input.dat
  tests/cookbook/manual-fd-hess-grad/input.dat
Labels: testing

#2821 support two qca branches
  .github/workflows/ecosystem.yml
  doc/sphinxman/source/nitpick-exceptions
  psi4/driver/driver_cbs.py
  psi4/driver/task_base.py
  pytest.ini
  tests/pytests/addons.py
  tests/pytests/test_qcfractal.py
Labels: testing, external-interface

#2822 Add deprecation message to schmidt_add in libqt
  psi4/src/psi4/libqt/blas_intfc.cc
  psi4/src/psi4/libqt/qt.h
Labels: api

#2818 `cc` Lagrangian and OPDM to Matrix; UHF Bugfix
  psi4/src/psi4/cc/ccdensity/CMakeLists.txt
  psi4/src/psi4/cc/ccdensity/MOInfo.h
  psi4/src/psi4/cc/ccdensity/add_core_ROHF.cc
  psi4/src/psi4/cc/ccdensity/add_ref_RHF.cc
  psi4/src/psi4/cc/ccdensity/add_ref_ROHF.cc
  psi4/src/psi4/cc/ccdensity/add_ref_UHF.cc
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/dump_RHF.cc
  psi4/src/psi4/cc/ccdensity/dump_ROHF.cc
  psi4/src/psi4/cc/ccdensity/dump_UHF.cc
  psi4/src/psi4/cc/ccdensity/kinetic.cc
  psi4/src/psi4/cc/ccdensity/sortI.cc
  psi4/src/psi4/cc/ccdensity/sortI_RHF.cc
  psi4/src/psi4/cc/ccdensity/sortI_ROHF.cc
  psi4/src/psi4/cc/ccdensity/sortI_UHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_RHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_ROHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_UHF.cc
  psi4/src/psi4/cc/ccdensity/to_matrix.cc
  psi4/src/psi4/libmints/deriv.cc
  tests/cc56/input.dat
  tests/pytests/test_dipoles.py
Labels: cc, correctness-error, cleanup

#2780 Close #2779
  psi4/src/psi4/detci/set_ciblks.cc
Labels: bug

#2816 IncFock Standardization Part 3: DFJCOSK
  doc/sphinxman/source/scf.rst
  psi4/src/export_fock.cc
  psi4/src/psi4/libfock/DFJCOSK.cc
  psi4/src/psi4/libfock/jk.h
  psi4/src/read_options.cc
  tests/pytests/test_dfjcosk.py
Labels: scf

#2824 Comment `compute_V`; Parallelize UKS `compute_V`
  psi4/src/psi4/libfock/dft_integrators.h
  psi4/src/psi4/libfock/points.h
  psi4/src/psi4/libfock/v.cc
  psi4/src/psi4/libfock/v.h
  psi4/src/psi4/libfunctional/superfunctional.h
Labels: parallelism, cleanup, dft, efficiency

#2791 allow and prefer simple-dftd3 and mctc-gcp
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/ecosystem.yml
  conda/win/meta.yaml
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/dftd3.rst
  doc/sphinxman/source/fisapt.rst
  doc/sphinxman/source/gcp.rst
  doc/sphinxman/source/glossary_psivariables.rst
  external/upstream/qcengine/CMakeLists.txt
  psi4/driver/procrouting/dft/dh_functionals.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc_util.py
  psi4/driver/qcdb/molecule.py
  psi4/share/psi4/fsapt/fsapt.py
  pytest.ini
  tests/dftd3/energy/input.dat
  tests/dftd3/grad/input.dat
  tests/dftd3/psithon2/input.dat
  tests/dftd3/psithon2/test_input.py
  tests/dftd3/version/input.dat
  tests/fsaptd-terms/fsapt-ref/Empirical_Disp.dat
  tests/gcp/hf3c/input.dat
  tests/gcp/pbeh3c/input.dat
  tests/psithon2/test_input.py
  tests/pytests/addons.py
  tests/pytests/test_addons.py
  tests/pytests/test_qcng_dftd3_mp2d.py
Labels: feature, external-interface, dft, driver

#2817 Libxc6, take 2
  doc/sphinxman/source/conda.rst
  doc/sphinxman/source/introduction.rst
  external/upstream/libxc/CMakeLists.txt
  external/upstream/pybind11/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver_nbody_multilevel.py
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.h
Labels: build

#2829 Close #2828
  tests/matrix1/input.dat
Labels: testing, correctness-error

#2832 `UV::compute_Vx` Bugfix
  psi4/src/psi4/libfock/v.cc
Labels: correctness-error, dft

#2835 ecosys gha on qcarchive next
  .github/workflows/ecosystem.yml
Labels: testing, external-interface

#2827 Fixes orbital read for finite difference hessian
  psi4/driver/driver_findif.py
  tests/CMakeLists.txt
  tests/opt16/CMakeLists.txt
  tests/opt16/input.dat
  tests/opt16/log.ref
  tests/opt16/output.ref
  tests/opt16/test_input.py
Labels: bug, optking
