Repository psi4/psi4, pull requests merged in 2022-02, with the labels that each got.

#2418 Silence sphinx warnings
  tests/frac-sym/input.dat
  tests/fsapt-ext-abc/input.dat
  tests/fsapt-ext-abc2/input.dat
  tests/mom-h2o-3/input.dat
  tests/mom-h2o-4/input.dat
  tests/scf-level-shift-cuhf/input.dat
  tests/scf-level-shift-rks/input.dat
  tests/scf-level-shift-rohf/input.dat
  tests/scf-level-shift-uhf/input.dat
  tests/scf-response3/input.dat
Labels: documentation, cleanup

#2420 Update dftensor.h
  psi4/src/psi4/lib3index/dftensor.h
Labels: api

#2423 Deprecate unused Deriv types
  psi4/src/psi4/libmints/deriv.h
Labels: api, libmints

#2422 fix docs warnings
  doc/sphinxman/source/basissets.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/conda.rst
  doc/sphinxman/source/libint.rst
  doc/sphinxman/source/manage_release.rst
  doc/sphinxman/source/psiapi.ipynb
Labels: documentation

#2424 Deprecate `Wavefunction.density_fitted`
  psi4/src/psi4/libmints/wavefunction.h
Labels: api, wavefunction

#2425 SCF Density Cleanup
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rhf.h
  psi4/src/psi4/scfgrad/scf_grad.cc
Labels: scf, cleanup

#2421 `fnocc` mini-cleanup
  psi4/src/psi4/fnocc/opdm.cc
Labels: fnocc, cleanup

#2419 Deprecate Built-In ADC
  doc/sphinxman/source/adc.rst
  psi4/driver/procrouting/proc.py
  psi4/src/read_options.cc
  tests/adc1/input.dat
  tests/adc2/input.dat
Labels: Alert!, adc

#2320 A/E DIIS
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/diis.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/driver/procrouting/scf_proc/subclass_methods.py
  psi4/src/psi4/libdiis/diismanager.h
  psi4/src/psi4/libscf_solver/cuhf.cc
  psi4/src/psi4/libscf_solver/cuhf.h
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/psi4/libscf_solver/rhf.cc
  psi4/src/psi4/libscf_solver/rhf.h
  psi4/src/psi4/libscf_solver/rohf.cc
  psi4/src/psi4/libscf_solver/rohf.h
  psi4/src/psi4/libscf_solver/uhf.cc
  psi4/src/psi4/libscf_solver/uhf.h
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/aediis-1/CMakeLists.txt
  tests/aediis-1/input.dat
  tests/aediis-1/output.ref
  tests/aediis-2/CMakeLists.txt
  tests/aediis-2/input.dat
  tests/aediis-2/output.ref
Labels: scf, feature

#2435 Fix bug in MemDFJK afflicting TDDFT
  psi4/src/psi4/lib3index/dfhelper.cc
  psi4/src/psi4/lib3index/dfhelper.h
  tests/CMakeLists.txt
  tests/tdscf-6/CMakeLists.txt
  tests/tdscf-6/input.dat
  tests/tdscf-6/output.ref
Labels: Alert!, backport, correctness-error, dft

#2434 Change `ccdensity` Keywords Around OPDM Relaxation
  psi4/driver/procrouting/proc.py
  psi4/src/psi4/cc/ccdensity/CMakeLists.txt
  psi4/src/psi4/cc/ccdensity/MOInfo.h
  psi4/src/psi4/cc/ccdensity/Params.h
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/get_moinfo.cc
  psi4/src/psi4/cc/ccdensity/get_params.cc
  psi4/src/psi4/cc/ccdensity/to_matrix.cc
  psi4/src/psi4/libqt/dx_write.cc
  psi4/src/read_options.cc
  tests/pytests/test_dipoles.py
Labels: api, cc

#2437 Expose reset_subspace to C++ for plugins
  psi4/src/psi4/libdiis/diismanager.cc
  psi4/src/psi4/libdiis/diismanager.h
Labels: api

#2438 Lose `*` in `ccdensity`
  psi4/src/psi4/cc/ccdensity/MOInfo.h
  psi4/src/psi4/cc/ccdensity/build_A_ROHF.cc
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/dump_RHF.cc
  psi4/src/psi4/cc/ccdensity/dump_ROHF.cc
  psi4/src/psi4/cc/ccdensity/dump_UHF.cc
  psi4/src/psi4/cc/ccdensity/ex_sort_td_rohf.cc
  psi4/src/psi4/cc/ccdensity/ex_sort_td_uhf.cc
  psi4/src/psi4/cc/ccdensity/fold_RHF.cc
  psi4/src/psi4/cc/ccdensity/fold_ROHF.cc
  psi4/src/psi4/cc/ccdensity/fold_UHF.cc
  psi4/src/psi4/cc/ccdensity/get_moinfo.cc
  psi4/src/psi4/cc/ccdensity/norm.cc
  psi4/src/psi4/cc/ccdensity/sortI_RHF.cc
  psi4/src/psi4/cc/ccdensity/sortI_ROHF.cc
  psi4/src/psi4/cc/ccdensity/sortI_UHF.cc
  psi4/src/psi4/cc/ccdensity/sort_ltd_rohf.cc
  psi4/src/psi4/cc/ccdensity/sort_ltd_uhf.cc
  psi4/src/psi4/cc/ccdensity/sort_rtd_rohf.cc
  psi4/src/psi4/cc/ccdensity/sort_rtd_uhf.cc
  psi4/src/psi4/cc/ccdensity/sortone_RHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_ROHF.cc
  psi4/src/psi4/cc/ccdensity/sortone_UHF.cc
  psi4/src/psi4/cc/ccdensity/to_matrix.cc
Labels: cc, cleanup

#2441 Update diismanager.cc
  psi4/src/psi4/libdiis/diismanager.cc
Labels: crash

#2440 Migrate energy-based `cc` tests to new standard
  tests/cc11/CMakeLists.txt
  tests/cc11/input.dat
  tests/cc11/output.ref
  tests/cc19/output.ref
  tests/cc22/input.dat
  tests/cc28/output.ref
  tests/cc30/output.ref
  tests/cc31/output.ref
  tests/cc34/output.ref
  tests/cc36/CMakeLists.txt
  tests/cc36/input.dat
  tests/cc36/output.ref
  tests/cc37/CMakeLists.txt
  tests/cc37/input.dat
  tests/cc37/output.ref
  tests/cc40/output.ref
  tests/cc41/output.ref
  tests/cc42/output.ref
  tests/cc43/output.ref
  tests/cc47/output.ref
  tests/cc48/output.ref
  tests/cc49/CMakeLists.txt
  tests/cc49/input.dat
  tests/cc49/output.ref
  tests/cc50/CMakeLists.txt
  tests/cc50/input.dat
  tests/cc50/output.ref
  tests/cc51/CMakeLists.txt
  tests/cc51/input.dat
  tests/cc51/output.ref
  tests/cc52/output.ref
  tests/cc55/output.ref
  tests/cc8/CMakeLists.txt
  tests/cc8/input.dat
  tests/cc8/output.ref
  tests/cc9/CMakeLists.txt
  tests/cc9/input.dat
  tests/cc9/output.ref
Labels: testing, cc

#2444 Revision to previous fnocc cleanup
  psi4/src/psi4/fnocc/opdm.cc
  tests/cepa1/CMakeLists.txt
  tests/cepa2/CMakeLists.txt
  tests/cepa3/CMakeLists.txt
Labels: bug, fnocc

#2443 Add LR Overlap Psivar
  doc/sphinxman/source/glossary_psivariables.rst
  psi4/src/psi4/cc/cclambda/CMakeLists.txt
  psi4/src/psi4/cc/cclambda/Params.h
  psi4/src/psi4/cc/cclambda/cclambda.cc
  psi4/src/psi4/cc/cclambda/overlap.cc
  psi4/src/psi4/cc/cclambda/overlap_LAMPS.cc
  tests/cc18/input.dat
  tests/cc18/output.ref
Labels: testing, api, cc

#2446 fix molden and nbody conv tests
  tests/nbody-vmfc-hessian/input.dat
  tests/pytests/test_molden_writer.py
  tests/pytests/test_molden_writer/dorbs_cartesian.ref
  tests/pytests/test_molden_writer/dorbs_spherical.ref
  tests/pytests/test_molden_writer/dovirt_false.ref
  tests/pytests/test_molden_writer/h2o_normal.ref
  tests/pytests/test_molden_writer/orbso_density.ref
  tests/pytests/test_molden_writer/orbso_detci.ref
  tests/pytests/test_molden_writer/ref_rohf.ref
  tests/pytests/test_molden_writer/ref_uhf.ref
  tests/pytests/test_molden_writer/sym_trivial.ref
Labels: testing

#2447 Port `cc19`, `cc28`, modify `cc29`
  psi4/src/psi4/cc/cclambda/cclambda.cc
  tests/cc19/CMakeLists.txt
  tests/cc19/input.dat
  tests/cc19/output.ref
  tests/cc28/CMakeLists.txt
  tests/cc28/input.dat
  tests/cc28/output.ref
  tests/cc29/input.dat
  tests/cc29/output.ref
Labels: testing, cc

#2448 Docs Fix Take 2
  psi4/src/psi4/cc/cclambda/cclambda.cc
Labels: documentation

#2451 Add Spec. Rot. Origin Dependence Psivar
  doc/sphinxman/source/glossary_psivariables.rst
  psi4/src/psi4/cc/ccresponse/optrot.cc
  tests/cc29/input.dat
  tests/cc29/output.ref
Labels: testing, api, cc

#2384 conda win back to avx
  .azure-pipelines/azure-pipelines-windows.yml
  CMakeLists.txt
  cmake/xhost.cmake
  psi4/CMakeLists.txt
Labels: build

#2415 Update azure-pipelines-windows.yml
  .azure-pipelines/azure-pipelines-windows.yml
Labels: build

#2456 `cc29`, `cc30`, `cc31` improvements
  tests/cc29/input.dat
  tests/cc29/output.ref
  tests/cc30/CMakeLists.txt
  tests/cc30/input.dat
  tests/cc30/output.ref
  tests/cc31/CMakeLists.txt
  tests/cc31/input.dat
  tests/cc31/output.ref
Labels: testing, cc
