Repository psi4/psi4, pull requests merged in 2022-04, with the labels that each got.

#2512 add logging
  .gitignore
  CMakeLists.txt
  doc/sphinxman/source/build_faq.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/external.rst
  psi4/__init__.py
  psi4/driver/__init__.py
  psi4/driver/driver.py
  psi4/extras.py
  psi4/run_psi4.py
Labels: python

#2529 Miscellaneous JK Improvements
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/export_fock.cc
  psi4/src/psi4/libfock/DirectJK.cc
  psi4/src/psi4/libfock/DiskDFJK.cc
  psi4/src/psi4/libfock/DiskJK.cc
  psi4/src/psi4/libfock/GTFockJK.cc
  psi4/src/psi4/libfock/MemDFJK.cc
  psi4/src/psi4/libfock/PKJK.cc
  psi4/src/psi4/libfock/jk.cc
  psi4/src/psi4/libfock/jk.h
Labels: scf

#2534 Make OEProp names flexible, to fix CC prop name bug.
  psi4/driver/procrouting/proc.py
  psi4/src/export_oeprop.cc
  psi4/src/psi4/libmints/oeprop.cc
  psi4/src/psi4/libmints/oeprop.h
  tests/cc46/input.dat
  tests/cc46/output.ref
Labels: api, cc, libmints

#2540 more installed windows path adjustments
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/ecosystem.yml
  conda/win/meta.yaml
  psi4/__init__.py
  tests/fsapt-ext-abc-au/test_input.py
  tests/fsapt-ext-abc/test_input.py
  tests/fsapt-ext-abc2/test_input.py
  tests/fsapt-terms/test_input.py
  tests/pytests/addons.py
Labels: build

#2544 findif number and nbody number and testing label.
  psi4/driver/driver.py
  pytest.ini
  tests/cbs-xtpl-gradient/input.dat
  tests/cbs-xtpl-nbody/CMakeLists.txt
  tests/cbs-xtpl-nbody/test_input.py
  tests/cc7/input.dat
  tests/dfmp2-1/CMakeLists.txt
  tests/dfmp2-1/test_input.py
  tests/dfmp2-ecp/CMakeLists.txt
  tests/dfmp2-ecp/input.dat
  tests/dfmp2-ecp/test_input.py
  tests/dfmp2-fc/CMakeLists.txt
  tests/dfmp2-fc/test_input.py
  tests/dft-custom-dhdf/CMakeLists.txt
  tests/dft-custom-dhdf/test_input.py
  tests/dft-dsd/CMakeLists.txt
  tests/dft-dsd/test_input.py
  tests/dft-freq/input.dat
  tests/fd-freq-energy-large/CMakeLists.txt
  tests/fd-freq-energy/input.dat
  tests/fd-freq-gradient/input.dat
  tests/fd-gradient/input.dat
  tests/mp2-def2/CMakeLists.txt
  tests/mp2-def2/test_input.py
  tests/nbody-convergence/CMakeLists.txt
  tests/nbody-convergence/test_input.py
  tests/nbody-cp-gradient/test_input.py
  tests/nbody-freq/test_input.py
  tests/nbody-he-cluster/test_input.py
  tests/nbody-hessian/test_input.py
  tests/nbody-intermediates/test_input.py
  tests/nbody-nocp-gradient/input.dat
  tests/nbody-nocp-gradient/test_input.py
  tests/nbody-vmfc-gradient/test_input.py
  tests/nbody-vmfc-hessian/test_input.py
  tests/pytests/test_addons.py
  tests/pytests/test_addons_qcschema.py
  tests/pytests/test_dft_benchmarks.py
  tests/pytests/test_nbody.py
  tests/pytests/test_nbody_multi_level_qcschema.py
  tests/pytests/test_psi4.py
  tests/tu6-cp-ne2/CMakeLists.txt
  tests/tu6-cp-ne2/test_input.py
Labels: python

#2546 bump ambit, clear addons from azure
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  external/upstream/ambit/CMakeLists.txt
  psi4/CMakeLists.txt
Labels: build

#2541 Renaming of excited states dipoles
  doc/sphinxman/source/glossary_psivariables.rst
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/proc.py
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/cc/ccdensity/Params.h
  psi4/src/psi4/cc/ccdensity/ccdensity.cc
  psi4/src/psi4/cc/ccdensity/ccdensity.h
  psi4/src/psi4/cc/ccdensity/ex_oscillator_strength.cc
  psi4/src/psi4/cc/ccdensity/ex_rotational_strength.cc
  psi4/src/psi4/cc/ccdensity/wfn_saver.cc
  psi4/src/psi4/cc/cceom/diag.cc
  psi4/src/psi4/cc/ccwave.h
  psi4/src/psi4/libmints/wavefunction.h
  tests/cc46/CMakeLists.txt
  tests/cc46/input.dat
  tests/cc46/output.ref
  tests/cc48/CMakeLists.txt
  tests/cc48/input.dat
  tests/cc48/output.ref
  tests/cc56/input.dat
  tests/cc56/output.ref
Labels: testing, api, cc

#2551 `autotest` Shall Die, Plus Pair Energies
  cmake/TestingMacros.cmake
  doc/sphinxman/source/glossary_psivariables.rst
  psi4/src/psi4/cc/ccenergy/MOInfo.h
  psi4/src/psi4/cc/ccenergy/Params.h
  psi4/src/psi4/cc/ccenergy/ccenergy.cc
  psi4/src/psi4/cc/ccenergy/get_moinfo.cc
  psi4/src/psi4/cc/ccenergy/get_params.cc
  psi4/src/psi4/cc/ccenergy/mp2_energy.cc
  psi4/src/psi4/cc/ccenergy/pair_energies.cc
  psi4/src/psi4/cc/ccwave.h
  psi4/src/read_options.cc
  tests/CMakeLists.txt
  tests/cc34/CMakeLists.txt
  tests/cc34/input.dat
  tests/cc34/output.ref
  tests/psitest.pl
  tests/runtest.py
Labels: testing
