Repository psi4/psi4, pull requests merged in 2022-01, with the labels that each got.

#2391 detect cppe module not lib
  CMakeLists.txt
  external/upstream/cppe/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/procrouting/response/scf_response.py
  psi4/psi4Config.cmake.in
Labels: build, external-interface

#2397 Misc. testing changes
  psi4/driver/p4util/testing.py
  psi4/driver/qcdb/testing.py
  tests/pytests/test_testing.py
Labels: testing

#2400 Update driver.py
  psi4/driver/driver.py
Labels: bug

#2392 c++17
  CMakeLists.txt
  psi4/src/CMakeLists.txt
  psi4/src/export_cubeprop.cc
  psi4/src/export_fock.cc
  psi4/src/export_functional.cc
  psi4/src/export_mints.cc
  psi4/src/export_pcm.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/libmints/CMakeLists.txt
  psi4/src/psi4/libmints/eri.cc
  psi4/src/psi4/libmints/eribase.cc
Labels: build

#2409 Fix docs
  doc/sphinxman/source/occ.rst
Labels: documentation
