Repository psi4/psi4, pull requests merged in 2023-12, with the labels that each got.

#3090 qcfractal v0.52
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/ecosystem.yml
  CMakeLists.txt
  README.md
  codedeps.yaml
  psi4/driver/task_base.py
Labels: schema

#3079 Documentation Updates for CompositeJK
  doc/sphinxman/source/scf.rst
Labels: documentation

#2842 Adds r2SCAN hybrids; r2SCAN-3c and B97-3c
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  codedeps.yaml
  doc/sphinxman/source/basissets_tables.rst
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/dftd3.rst
  doc/sphinxman/source/gcp.rst
  doc/sphinxman/source/introduction.rst
  external/upstream/libxc/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/driver_util.py
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/driver/procrouting/dft/gga_functionals.py
  psi4/driver/procrouting/dft/hyb_functionals.py
  psi4/driver/procrouting/dft/libxc_functionals.py
  psi4/driver/procrouting/dft/mgga_functionals.py
  psi4/driver/procrouting/empirical_dispersion.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_table.py
  psi4/driver/qcdb/basislistother.py
  psi4/share/psi4/basis/def2-mtzvp.gbs
  psi4/share/psi4/basis/def2-mtzvpp.gbs
  psi4/share/psi4/basis/vdzp.gbs
  psi4/src/export_functional.cc
  psi4/src/psi4/libfunctional/superfunctional.cc
  psi4/src/psi4/libfunctional/superfunctional.h
  pytest.ini
  tests/dftd4/CMakeLists.txt
  tests/dftd4/r2scan/CMakeLists.txt
  tests/dftd4/r2scan/input.dat
  tests/dftd4/r2scan/test_input.py
  tests/docs-dft/input.dat
  tests/gcp/CMakeLists.txt
  tests/gcp/b973c/CMakeLists.txt
  tests/gcp/b973c/input.dat
  tests/gcp/b973c/test_input.py
  tests/gcp/r2scan3c/CMakeLists.txt
  tests/gcp/r2scan3c/input.dat
  tests/gcp/r2scan3c/test_input.py
  tests/pytests/conftest.py
  tests/pytests/test_dftd3.py
Labels: enhancement, external-interface, dft

#3097 Fix Python3 compatibility in vmd_cube.py
  psi4/share/psi4/scripts/vmd_cube.py
Labels: backport

#3105 SAPT0 CPHF Uniform Treatment
  doc/sphinxman/source/sapt.rst
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/sapt/sapt_jk_terms.py
  psi4/driver/procrouting/sapt/sapt_proc.py
  psi4/src/core.cc
  psi4/src/psi4/fisapt/fisapt.cc
  psi4/src/psi4/libsapt_solver/ind20.cc
  psi4/src/psi4/libsapt_solver/sapt0.cc
  psi4/src/psi4/libsapt_solver/sapt0.h
  psi4/src/psi4/libsapt_solver/sapt2.cc
  psi4/src/psi4/libsapt_solver/usapt0.cc
  psi4/src/read_options.cc
Labels: sapt

#3103 fix libxc min
  codedeps.yaml
  external/upstream/libxc/CMakeLists.txt
  psi4/CMakeLists.txt
  tests/pytests/test_erisieve.py
  tests/pytests/test_np_views.py
Labels: backport
