Repository psi4/psi4, pull requests merged in 2023-02, with the labels that each got.

#2863 Lots of DFT Commenting
  psi4/src/psi4/libfock/dft_integrators.h
  psi4/src/psi4/libfock/points.h
  psi4/src/psi4/libfock/v.cc
  psi4/src/psi4/libfock/v.h
  psi4/src/psi4/libfunctional/superfunctional.h
Labels: cleanup, dft

#2849 UKS-GGA: TDDFT and Stability Analysis
  doc/sphinxman/source/tdscf.rst
  psi4/driver/procrouting/response/scf_response.py
  psi4/driver/procrouting/scf_proc/subclass_methods.py
  tests/pytests/tdscf_reference_data.json
  tests/pytests/test_tdscf_excitations.py
Labels: feature, dft

#2877 Libxc citation
  psi4/driver/procrouting/dft/dft_builder.py
  psi4/src/export_functional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.h
Labels: dft

#2874 Rename 'build_disp_functor' to 'build_functional_and_disp'
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_util.py
Labels: cleanup

#2881 Clarify SCF Guess Documentation
  doc/sphinxman/source/scf.rst
  psi4/src/read_options.cc
Labels: documentation

#2886 Correct erroneous test values.
  tests/pytests/tdscf_reference_data.json
Labels: testing, dft

#2887 Add DAXPBY to Psi and to the Vector class.
  psi4/src/psi4/libmints/vector.cc
  psi4/src/psi4/libmints/vector.h
  psi4/src/psi4/libqt/blas_intfc.cc
  psi4/src/psi4/libqt/blas_intfc_mangle.h
  psi4/src/psi4/libqt/qt.h
Labels: libmints

#2888 Add build_polarized function.
  psi4/src/psi4/libfunctional/LibXCfunctional.cc
  psi4/src/psi4/libfunctional/LibXCfunctional.h
  psi4/src/psi4/libfunctional/functional.h
  psi4/src/psi4/libfunctional/superfunctional.cc
  psi4/src/psi4/libfunctional/superfunctional.h
Labels: dft
