Repository psi4/psi4, pull requests merged in 2023-09, with the labels that each got.

#3043 fix timer hostname bug
  psi4/src/psi4/libciomr/tstart.cc
  psi4/src/psi4/libqt/timer.cc
Labels: bug, backport

#3044 Amend #3043 by allowing a longer hostname and simplifying the code.
  psi4/src/psi4/libciomr/tstart.cc
  psi4/src/psi4/libqt/timer.cc
Labels: backport

#2982 CABS, rework build_cabs_space
  psi4/driver/qcdb/libmintsbasisset.py
  psi4/share/psi4/basis/NOTES
  psi4/share/psi4/basis/aug-cc-pv5z-optri.gbs
  psi4/share/psi4/basis/aug-cc-pvdz-optri.gbs
  psi4/share/psi4/basis/aug-cc-pvqz-optri.gbs
  psi4/share/psi4/basis/aug-cc-pvtz-optri.gbs
  psi4/share/psi4/basis/cc-pcvdz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pcvdz-f12.gbs
  psi4/share/psi4/basis/cc-pcvqz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pcvqz-f12.gbs
  psi4/share/psi4/basis/cc-pcvtz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pcvtz-f12.gbs
  psi4/share/psi4/basis/cc-pv5z-f12.gbs
  psi4/share/psi4/basis/cc-pvdz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pvdz-f12.gbs
  psi4/share/psi4/basis/cc-pvqz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pvqz-f12.gbs
  psi4/share/psi4/basis/cc-pvtz-f12-optri.gbs
  psi4/share/psi4/basis/cc-pvtz-f12.gbs
  psi4/src/export_mints.cc
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/orbitalspace.cc
  psi4/src/psi4/libmints/orbitalspace.h
  tests/pytests/test_orbitalspace.py
Labels: feature

#3048 fix docs build after QCArchive documentation shuffle
  doc/sphinxman/source/conf.py.in
Labels: documentation, backport
