Repository psi4/psi4, pull requests merged in 2023-08, with the labels that each got.

#3019 adapt for pydantic v1 and v2
  .azure-pipelines/azure-pipelines-linux.yml
  CMakeLists.txt
  devtools/conda-envs/docs-cf.yaml
  doc/sphinxman/source/build_obtaining.rst
  doc/sphinxman/source/build_planning.rst
  doc/sphinxman/source/fisapt.rst
  external/upstream/ambit/CMakeLists.txt
  external/upstream/dkh/CMakeLists.txt
  external/upstream/pcmsolver/CMakeLists.txt
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/driver/driver_cbs.py
  psi4/driver/driver_findif.py
  psi4/driver/driver_nbody.py
  psi4/driver/task_base.py
Labels: backport

#3008 pytest not really reqd
  psi4/driver/procrouting/empirical_dispersion.py
Labels: backport

#2968 Update gdma to v2.3; convert to runtime
  .github/workflows/ecosystem.yml
  CMakeLists.txt
  external/upstream/gdma/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/__init__.py
  psi4/driver/driver.py
  psi4/driver/procrouting/proc.py
  psi4/extras.py
  psi4/src/core.cc
  psi4/src/psi4/CMakeLists.txt
  psi4/src/psi4/gdma_interface/CMakeLists.txt
  psi4/src/psi4/gdma_interface/wrapper.cc
  tests/gdma/gdma1/input.dat
  tests/pytests/addons.py
Labels: build, external-interface

#3024 Remove new's in SOBasis
  psi4/src/psi4/libmints/potential.cc
  psi4/src/psi4/libmints/sobasis.cc
  psi4/src/psi4/libmints/sobasis.h
  psi4/src/psi4/libmints/sointegral.cc
  psi4/src/psi4/libmints/wavefunction.cc
Labels: libmints, cleanup

#3022 update to qcengine v0.28
  external/upstream/qcengine/CMakeLists.txt
  tests/pytests/standard_suite_ref_local.py
Labels: testing, cleanup

#3029 fix_orientation docstring
  psi4/src/export_mints.cc
Labels: documentation

#3027 pull all py-side physconst from single instance
  .github/workflows/ecosystem.yml
  devtools/conda-envs/docs-cf.yaml
  doc/sphinxman/source/nitpick-exceptions
  external/upstream/qcengine/CMakeLists.txt
  psi4/driver/__init__.py
  psi4/driver/constants.py
  psi4/driver/driver.py
  psi4/driver/driver_findif.py
  psi4/driver/mdi_engine.py
  psi4/driver/molutil.py
  psi4/driver/procrouting/proc.py
  psi4/driver/procrouting/proc_util.py
  psi4/driver/procrouting/solvent/ddx.py
  psi4/driver/procrouting/solvent/pol_embed.py
  psi4/driver/qcdb/__init__.py
  psi4/driver/qcdb/bfs.py
  psi4/driver/qcdb/cfour.py
  psi4/driver/qcdb/constants.py
  psi4/driver/qcdb/libmintsmolecule.py
  psi4/driver/qcdb/molecule.py
  psi4/driver/qcdb/orca.py
  psi4/driver/qcdb/parker.py
  psi4/driver/qcdb/pytest/addons.py
  psi4/driver/qcdb/pytest/test_bfs.py
  psi4/driver/qcdb/pytest/test_from_string.py
  psi4/driver/qcdb/pytest/test_mints4.py
  psi4/driver/qcdb/pytest/test_mints5_molecule_symmetry.py
  psi4/driver/qcdb/vib.py
Labels: cleanup, driver

#2931 COSX Reformulation for Negative Grid Weights
  psi4/src/psi4/libfock/CompositeJK.cc
Labels: scf

#3039 Libint2 native implementation of the fitted SAP guess
  doc/sphinxman/source/bibliography.rst
  doc/sphinxman/source/scf.rst
  psi4/driver/procrouting/proc.py
  psi4/share/psi4/basis/sap_grasp_large.gbs
  psi4/share/psi4/basis/sap_grasp_small.gbs
  psi4/share/psi4/basis/sap_helfem_large.gbs
  psi4/share/psi4/basis/sap_helfem_small.gbs
  psi4/src/psi4/libmints/basisset.cc
  psi4/src/psi4/libmints/basisset.h
  psi4/src/psi4/libscf_solver/hf.cc
  psi4/src/psi4/libscf_solver/hf.h
  psi4/src/read_options.cc
  tests/scf-guess/input.dat
  tests/scf-guess/output.ref
Labels: backport, scf, feature
