Repository psi4/psi4, pull requests merged in 2023-01, with the labels that each got.

#2840 Fix DLPNO-MP2 Segfault with Cartesian Basis Sets
  psi4/src/psi4/libfock/points.cc
  tests/CMakeLists.txt
  tests/dlpnomp2-3/CMakeLists.txt
  tests/dlpnomp2-3/input.dat
  tests/dlpnomp2-3/output.ref
  tests/dlpnomp2-3/test_input.py
Labels: bug

#2834 Fix screening in Vx
  psi4/src/psi4/libfock/v.cc
  psi4/src/read_options.cc
  tests/pytests/standard_suite_ref_local.py
Labels: dft

#2845 np.float update
  .github/workflows/docs-pr.yml
  devtools/conda-envs/docs-cf.yaml
  psi4/driver/qcdb/bfs.py
Labels: build

#2855 ints and master docs fixes
  .github/workflows/docs.yml
  psi4/driver/procrouting/solvent/ddx.py
  psi4/src/psi4/libmints/mintshelper.cc
  psi4/src/psi4/libmints/numinthelper.h
  psi4/src/psi4/libmints/potentialint.cc
  psi4/src/psi4/libmints/potentialint.h
Labels: build-blocker

#2837 Remove deprecated overloads of Matrix::diagonalize
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/matrix.h
Labels: libmints, cleanup

#2838 Remove deprecated rsp diagonalizer
  psi4/src/psi4/libciomr/CMakeLists.txt
  psi4/src/psi4/libciomr/libciomr.h
  psi4/src/psi4/libciomr/rsp.cc
  psi4/src/psi4/libciomr/tqli.cc
  psi4/src/psi4/libciomr/tred2.cc
Labels: cleanup

#2814 Remove commented-out ras_set() and ras_set2 functions
  psi4/src/psi4/libqt/qt.h
  psi4/src/psi4/libqt/ras_set.cc
Labels: cleanup, detci

#2836 Add large atoms test
  psi4/driver/procrouting/proc.py
  tests/large-atoms/CMakeLists.txt
  tests/large-atoms/input.dat
  tests/pytests/test_large_atoms.py
Labels: testing, ecpint-needed

#2860 Restore DCT-06 with spin restriction.
  psi4/src/psi4/dct/dct_compute_RHF.cc
  tests/CMakeLists.txt
  tests/dct12/CMakeLists.txt
  tests/dct12/input.dat
  tests/dct12/output.ref
  tests/dct12/test_input.py
Labels: testing, crash, dct
