Repository psi4/psi4, pull requests merged in 2023-11, with the labels that each got.

#3049 try new qcfractal 0.50
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/ecosystem.yml
  external/upstream/qcelemental/CMakeLists.txt
  external/upstream/qcengine/CMakeLists.txt
  psi4/__init__.py
  psi4/driver/task_base.py
  psi4/run_psi4.py
  tests/pytests/test_dipoles.py
Labels: backport

#3050 add Einsums to build system
  .azure-pipelines/azure-pipelines-windows.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs.yml
  .github/workflows/ecosystem.yml
  CMakeLists.txt
  external/common/hdf5/CMakeLists.txt
  external/common/lapack/CMakeLists.txt
  external/upstream/CMakeLists.txt
  external/upstream/einsums/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/extras.py
  psi4/src/CMakeLists.txt
  psi4/src/core.cc
  psi4/src/psi4/CMakeLists.txt
  psi4/src/psi4/dummy_einsums/CMakeLists.txt
  psi4/src/psi4/dummy_einsums/ein_test.cc
  pytest.ini
  tests/pytests/addons.py
  tests/pytests/test_addons.py
Labels: build

#3078 Libint2 Generator
  external/upstream/libint2/CMakeLists.txt
Labels: build

#3052 Scf guess test
  psi4/driver/p4util/python_helpers.py
  psi4/driver/procrouting/scf_proc/scf_iterator.py
  psi4/src/core.cc
  psi4/src/psi4/libscf_solver/hf.cc
  tests/pytests/test_scf_options.py
  tests/scf-guess/input.dat
Labels: testing, scf

#3086 Fix `oeprop` argument case behavior
  psi4/driver/p4util/util.py
Labels: bug, property

#3088 Clean up leftover PRAGMA_WARNING manipulations from deboosting
  psi4/src/psi4/detci/ciwave.cc
  psi4/src/psi4/detci/ciwave.h
  psi4/src/psi4/detci/structs.h
  psi4/src/psi4/lib3index/cholesky.cc
  psi4/src/psi4/libdpd/dpd.h
  psi4/src/psi4/libfunctional/factory.cc
  psi4/src/psi4/libmints/basisset.h
  psi4/src/psi4/libmints/cdsalclist.h
  psi4/src/psi4/libmints/coordentry.h
  psi4/src/psi4/libmints/gridblock.h
  psi4/src/psi4/libmints/integral.h
  psi4/src/psi4/libmints/integraliter.cc
  psi4/src/psi4/libmints/kinetic.h
  psi4/src/psi4/libmints/nabla.h
  psi4/src/psi4/libmints/petitelist.h
  psi4/src/psi4/libmints/pointgrp.h
  psi4/src/psi4/libmints/sointegral.cc
  psi4/src/psi4/libmints/tracelessquadrupole.h
  psi4/src/psi4/libmints/writer.h
  psi4/src/psi4/liboptions/print.cc
  psi4/src/psi4/libpsi4util/process.h
  psi4/src/psi4/libpsio/change_namespace.cc
  psi4/src/psi4/libpsio/done.cc
  psi4/src/psi4/libpsio/filescfg.cc
  psi4/src/psi4/libpsio/get_numvols.cc
  psi4/src/psi4/libpsio/init.cc
  psi4/src/psi4/libpsio/open_check.cc
  psi4/src/psi4/libpsio/read.cc
  psi4/src/psi4/libpsio/tocclean.cc
  psi4/src/psi4/libpsio/tocdel.cc
  psi4/src/psi4/libpsio/tocprint.cc
  psi4/src/psi4/libpsio/tocscan.cc
  psi4/src/psi4/libpsio/tocwrite.cc
  psi4/src/psi4/libpsio/write.cc
  psi4/src/psi4/libpsio/write_entry.cc
  psi4/src/psi4/libpsio/zero_disk.cc
  psi4/src/psi4/psimrcc/blas_diis.cc
  psi4/src/psi4/psimrcc/matrix_memory_and_io.cc
  psi4/src/psi4/psimrcc/mrcc_Heff.cc
  psi4/src/psi4/psimrcc/mrcc_pert_triples.cc
  psi4/src/psi4/psimrcc/transform_block.cc
  psi4/src/psi4/psimrcc/transform_presort.cc
Labels: cleanup
