Repository psi4/psi4, pull requests merged in 2025-05, with the labels that each got.

#3282 Remove Deprecated Code
  external/downstream/v2rdm_casscf/CMakeLists.txt
  psi4/driver/driver.py
  psi4/driver/p4util/writer.py
  psi4/driver/procrouting/proc.py
  psi4/src/core.cc
  psi4/src/export_mints.cc
  psi4/src/export_wavefunction.cc
  psi4/src/psi4/dfocc/occ_iterations.cc
  psi4/src/psi4/dmrg/dmrg.h
  psi4/src/psi4/dmrg/dmrgscf.cc
  psi4/src/psi4/libfock/cubature.cc
  psi4/src/psi4/libfock/cubature.h
  psi4/src/psi4/libmints/matrix.cc
  psi4/src/psi4/libmints/matrix.h
  psi4/src/psi4/libmints/twobody.cc
  psi4/src/psi4/libmints/wavefunction.cc
  psi4/src/psi4/libmints/wavefunction.h
  psi4/src/psi4/libmints/writer.cc
  psi4/src/psi4/libmints/writer.h
  psi4/src/psi4/libsapt_solver/amplitudes.cc
  psi4/src/psi4/libsapt_solver/exch-ind30.cc
  psi4/src/psi4/libsapt_solver/ind30.cc
  psi4/src/psi4/libsapt_solver/sapt2p3.h
  psi4/src/psi4/mrcc/mrcc.cc
  tests/pytests/test_misc.py
Labels: external-interface, wavefunction, cleanup

#3286 cmake v4, test more deps w/latest hdf5 and numpy
  .azure-pipelines/azure-pipelines-linux.yml
  .github/workflows/ecosystem.yml
  CMakeLists.txt
  README.md
  codedeps.yaml
  doc/sphinxman/CMakeLists.txt
  external/downstream/v2rdm_casscf/CMakeLists.txt
  external/upstream/gau2grid/CMakeLists.txt
  external/upstream/gauxc/CMakeLists.txt
  external/upstream/libxc/CMakeLists.txt
  external/upstream/optking/CMakeLists.txt
  psi4/CMakeLists.txt
  psi4/extras.py
  psi4/psi4Config.cmake.in
  psi4/share/psi4/plugin/ambit/CMakeLists.txt.template
  psi4/share/psi4/plugin/aointegrals/CMakeLists.txt.template
  psi4/share/psi4/plugin/basic/CMakeLists.txt.template
  psi4/share/psi4/plugin/dfmp2/CMakeLists.txt.template
  psi4/share/psi4/plugin/mointegrals/CMakeLists.txt.template
  psi4/share/psi4/plugin/scf/CMakeLists.txt.template
  psi4/share/psi4/plugin/sointegrals/CMakeLists.txt.template
  psi4/share/psi4/plugin/wavefunction/CMakeLists.txt.template
  tests/pytests/test_addons_qcschema.py
  tests/pytests/test_ddx.py
Labels: build

#3288 DePointerDPD Warmup: `Dimension` for `cc`
  psi4/src/psi4/cc/ccdensity/Iab.cc
  psi4/src/psi4/cc/ccdensity/MOInfo.h
  psi4/src/psi4/cc/ccdensity/get_moinfo.cc
  psi4/src/psi4/cc/ccenergy/MOInfo.h
  psi4/src/psi4/cc/ccenergy/get_moinfo.cc
  psi4/src/psi4/cc/cceom/MOInfo.h
  psi4/src/psi4/cc/cceom/get_moinfo.cc
  psi4/src/psi4/cc/cchbar/MOInfo.h
  psi4/src/psi4/cc/cchbar/get_moinfo.cc
  psi4/src/psi4/cc/cclambda/MOInfo.h
  psi4/src/psi4/cc/cclambda/get_moinfo.cc
  psi4/src/psi4/cc/ccresponse/MOInfo.h
  psi4/src/psi4/cc/ccresponse/get_moinfo.cc
  psi4/src/psi4/cc/ccresponse/sort_pert.cc
  psi4/src/psi4/cc/cctriples/MOInfo.h
  psi4/src/psi4/cc/cctriples/get_moinfo.cc
  psi4/src/psi4/cctransort/cctransort.cc
  psi4/src/psi4/libdpd/dpd.h
  psi4/src/psi4/libdpd/init.cc
Labels: cc, cleanup
